<div class="d-flex justify-content-between py-4">
	<h3 id="idCaption"></h3>
	<h3><i class="far fa-clock pr-2"></i><span id="reloj"></span></h3>
</div>

<div id="data_Table" class="table-responsive text-lg divSala text-dark">
	<?php echo $this->data; ?>
</div>

<!-- <div class="container-fluid pt-4 my-auto d-flex justify-content-between">
	<div class="my-auto ">
		<img class="card-img-bottom" height="100px" src="<?php echo $this->baseUrl(); ?>/assets/img/msp.jpg" alt="MSP">
	</div>
	<div class="my-auto ">
		<img class="card-img-bottom" height="100px" src="<?php echo $this->baseUrl(); ?>/assets/img/todaunavida.png"
			alt="1">
	</div>
</div> -->