<div class=" d-flex justify-content-between align-middle pb-4">
  <h4 class="h4 text-capitalize text-dark"><?php echo $this->controlador; ?>
    <i class="fas fa-fw <?php echo $this->icono; ?> text-dark"></i></h4>
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb bg-transparent  text-xxs p-0 ">
      <li class="breadcrumb-item"><a href="<?php echo $this->baseUrl(); ?>/panel_de_control">
          <i class="fas fa-home "></i>Inicio</a></li>
      <li class="breadcrumb-item text-capitalize">
        <a href="<?php echo $this->baseUrl(); ?>/<?php echo $this->controlador; ?>">
          <i class="fas fa-fw <?php echo $this->icono; ?>"></i>
          <?php echo $this->controlador; ?></a></li>
      <li class="breadcrumb-item active text-capitalize" aria-current="page">
        <?php echo $this->accion; ?></li>
    </ol>
  </nav>

</div>

<div class="row">
  <!-- Earnings (Monthly) Card Example -->
  <div class="col-xl-3 col-md-6 mb-4">
    <div class="card lift border-left-primary shadow h-100 py-2">
      <div class="card-body">
        <div class="row no-gutters align-items-center">
          <div class="col mr-2">
            <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">Pacientes internos</div>
            <div class="h5 mb-0 font-weight-bold text-gray-800"><?php echo $this->cuenta_pacientes; ?></div>
          </div>
          <div class="col-auto">
            <i class="fas fa-user-tag fa-2x text-primary"></i>
          </div>
        </div>
      </div>
      <div class="card-footer bg-white text-center text-xs py-0">
        <a href="<?php echo $this->baseUrl();?>/listar_paciente" class="btn btn-link btn-sm py-0 text-decoration-none"
          data-toggle="tooltip" data-placement="right" title="Clic para visualizar">Ver Pacientes</a>
      </div>
    </div>
  </div>
  <!-- Earnings (Monthly) Card Example -->
  <div class="col-xl-3 col-md-6 mb-4">
    <div class="card lift border-left-secondary shadow h-100 py-2">
      <div class="card-body">
        <div class="row no-gutters align-items-center">
          <div class="col mr-2">
            <div class="text-xs font-weight-bold text-secondary text-uppercase mb-1">Camas disponibles</div>
            <div class="row no-gutters align-items-center">
              <div class="col-auto">
                <div class="h5 mb-0 mr-3 font-weight-bold text-gray-800">
                  <span id="cuentaCamasDisponibles"><?php echo $this->cuenta_camas_disp; ?></span>%</div>
              </div>
              <div class="col">
                <div class="progress progress-sm mr-2">
                  <div class="progress-bar bg-secondary" role="progressbar"
                    style='width: <?php echo $this->cuenta_camas_disp."%"; ?>'
                    aria-valuenow='<?php echo $this->cuenta_camas_disp; ?>' aria-valuemin="0" aria-valuemax="100"></div>
                </div>
              </div>
            </div>
          </div>
          <div class="col-auto">
            <i class="fas fa-bed fa-2x text-secondary"></i>

          </div>
        </div>
      </div>
      <div class="card-footer bg-white text-center text-xs py-0">
        <a href="<?php echo $this->baseUrl();?>/camas?op=Disponible"
          class="btn btn-link btn-sm py-0 text-decoration-none" data-toggle="tooltip" data-placement="right"
          title="Clic para visualizar">Ver Camas Disponibles</a>
      </div>
    </div>
  </div>
  <!-- Earnings (Monthly) Card Example -->
  <div class="col-xl-3 col-md-6 mb-4">
    <div class="card lift border-left-danger shadow h-100 py-2">
      <div class="card-body">
        <div class="row no-gutters align-items-center">
          <div class="col mr-2">
            <div class="text-xs font-weight-bold text-danger text-uppercase mb-1">Camas Ocupadas</div>
            <div class="row no-gutters align-items-center">
              <div class="col-auto">
                <div class="h5 mb-0 mr-3 font-weight-bold text-gray-800">
                  <span id="cuentaCamasOcupadas"><?php echo $this->cuenta_camas_ocup; ?></span>%</div>
              </div>
              <div class="col">
                <div class="progress progress-sm mr-2">
                  <div class="progress-bar bg-danger" role="progressbar"
                    style='width: <?php echo $this->cuenta_camas_ocup."%"; ?>'
                    aria-valuenow='<?php echo $this->cuenta_camas_ocup; ?>' aria-valuemin="0" aria-valuemax="100"></div>
                </div>
              </div>
            </div>
          </div>
          <div class="col-auto">
            <i class="fas fa-bed fa-2x text-danger"></i>
          </div>
        </div>
      </div>
      <div class="card-footer bg-white text-center text-xs py-0">
        <a href="<?php echo $this->baseUrl();?>/camas?op=Ocupada" class="btn btn-link btn-sm py-0 text-decoration-none"
          data-toggle="tooltip" data-placement="right" title="Clic para visualizar">Ver Camas Ocupadas</a>
      </div>
    </div>
  </div>
  <div class="col-xl-3 col-md-6 mb-4">
    <div class="card lift border-left-warning shadow h-100 py-2">
      <div class="card-body">
        <div class="row no-gutters align-items-center">
          <div class="col mr-2">
            <div class="text-xs font-weight-bold text-warning text-uppercase mb-1">En desinfeccion</div>
            <div class="row no-gutters align-items-center">
              <div class="col-auto">
                <div class="h5 mb-0 mr-3 font-weight-bold text-gray-800">
                  <span id="cuentaCamasDesinfeccion"><?php echo $this->cuenta_camas_desinf; ?></span>%
                </div>
              </div>
              <div class="col">
                <div class="progress progress-sm mr-2">
                  <div class="progress-bar bg-warning" role="progressbar"
                    style='width: <?php echo $this->cuenta_camas_desinf."%"; ?>'
                    aria-valuenow='<?php echo $this->cuenta_camas_desinf; ?>' aria-valuemin="0" aria-valuemax="100">
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="col-auto">
            <i class="fas fa-bed fa-2x text-warning"></i>

          </div>
        </div>
      </div>
      <div class="card-footer bg-white text-center text-xs py-0">
        <a href="<?php echo $this->baseUrl();?>/camas?op=Desinfeccion"
          class="btn btn-link btn-sm py-0 text-decoration-none" data-toggle="tooltip" data-placement="right"
          title="Clic para visualizar">Ver Camas en Desinfeccion</a>
      </div>
    </div>
  </div>

</div>

<div class="row">
  <div class="col-lg-9 ">
    <div class="card lift shadow mb-4  ">
      <!-- Card Header - Dropdown -->
      <div class="card-header d-flex flex-row align-items-center justify-content-between">
        <h6 class="m-0 font-weight-bold text-primary">Camas por especialidad</h6>
        <div class="dropdown no-arrow">
          <a class="dropdown-toggle px-4" href="#" onclick="camasPorServicio();">
            <i class="fas fa-sync-alt fa-sm fa-fw text-gray-400"></i>
          </a>
          <!-- <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown"
            aria-haspopup="true" aria-expanded="false">
            <i class="fas fa-filter fa-sm fa-fw text-gray-400"></i>
          </a>
          <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
            <div class="dropdown-header">Opciones:</div>
            <a class="dropdown-item" href="#" onclick="camasPorServicio(0);">Disponibles</a>
            <a class="dropdown-item" href="#" onclick="camasPorServicio(1);">Ocupadas</a>
            <a class="dropdown-item" href="#" onclick="camasPorServicio(2);">Desinfeccion</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#" onclick="camasPorServicio();">Todas</a>

          </div> -->
        </div>
      </div>
      <div class="card-body pt-0">
        <canvas id="myChart" width="130" height="50"></canvas>

      </div>
    </div>


  </div>
  <!-- Pie Chart -->
  <div class="col-lg-3">
    <div class="row">
      <div class="col-sm-12 mb-4">
        <div class="card lift border-left-success text-success shadow h-100 py-2">
          <div class="card-body">
            <div class="row no-gutters align-items-center">
              <div class="col mr-2">
                <div class="text-xs font-weight-bold text-success text-uppercase mb-1">Usuarios</div>
                <div class="h5 mb-0 font-weight-bold text-gray-800"><?php echo $this->cuenta_usuarios ?></div>
              </div>
              <div class="col-auto">
                <i class="fas fa-users fa-2x text-success"></i>
              </div>
            </div>
          </div>
          <div class="card-footer bg-white text-center text-xs py-0">
            <a href="<?php echo $this->baseUrl();?>/listar_usuarios"
              class="btn btn-link btn-sm py-0 text-decoration-none" data-toggle="tooltip" data-placement="right"
              title="Clic para visualizar">Ver Usuarios</a>
          </div>
        </div>
      </div>

    </div>
    <div class="row">
      <div class="col-sm-12 mb-4">
        <div class="card lift shadow  ">
          <!-- Card Header - Dropdown -->
          <div class="card-header d-flex flex-row align-items-center justify-content-between">
            <h6 class="m-0 font-weight-bold text-primary">Camas</h6>
            <div class="dropdown no-arrow">
              <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown"
                aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
              </a>
              <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in"
                aria-labelledby="dropdownMenuLink">
                <div class="dropdown-header">Dropdown Header:</div>
                <a class="dropdown-item" href="#">Action</a>
                <a class="dropdown-item" href="#">Another action</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#">Something else here</a>
              </div>
            </div>
          </div>
          <!-- Card Body -->
          <div class="card-body ">
            <canvas id="myPieChart"></canvas>
          </div>
        </div>
      </div>

    </div>


  </div>

</div>

<div class="row">
  <div class="col-xl-12 ">
    <div class="card shadow mb-4  ">
      <!-- Card Header - Dropdown -->
      <div class="card-header d-flex flex-row align-items-center justify-content-between">
        <h6 class="m-0 font-weight-bold text-primary">Mapa de pacientes y camas</h6>
        <div class="dropdown no-arrow">
          <a class="dropdown-toggle px-4" href="#" onclick="mapaDeCamas(0);">
            <i class="fas fa-sync-alt fa-sm fa-fw text-gray-400"></i>
          </a>
          <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown"
            aria-haspopup="true" aria-expanded="false">
            <i class="fas fa-filter fa-sm fa-fw text-gray-400"></i>
          </a>
          <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in " aria-labelledby="dropdownMenuLink">
            <div class="dropdown-header pl-4">Fecha:</div>

            <div class="dropdown-divider"></div>
            <a class="dropdown-item text-xxs pl-4" href="#" onclick="mapaDeCamas(0);">TODOS</a>

          </div>
        </div>
      </div>
      <div class="card-body divTarjeta text-xxs">
        <div id="data_MapaCamas"  >
        </div>
      </div>
      <div class="card-footer">
        <?php $obj = new Application_Model_DbTable_Especialidades();
              $datos = $obj->listar();
              if(isset($datos)): 
                foreach ($datos as $item): ?>
        <button type="button" class="btn btn-<?php echo $item->especialidad_color ?> btn-xs "
          onclick="mapaDeCamas('<?php echo $item->especialidad_id ?>');">
          <small><?php echo $item->especialidad_nombre ?></small>
        </button>
        <?php   endforeach;
               endif; ?>
        <button type="button" class="btn btn-light btn-xs" onclick="mapaDeCamas(0);">
          <small>TODOS</small></button>
      </div>
    </div>

  </div>
</div>
