<div class=" d-flex justify-content-between align-middle pb-4">
  <h4 class="h4 text-capitalize text-dark"><?php echo $this->controlador; ?>
    <i class="fas fa-fw <?php echo $this->icono; ?> text-dark"></i></h4>
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb bg-transparent  text-xxs p-0 ">
      <li class="breadcrumb-item"><a href="<?php echo $this->baseUrl(); ?>/panel_de_control">
          <i class="fas fa-home "></i>Inicio</a></li>
      <li class="breadcrumb-item text-capitalize">
        <a href="<?php echo $this->baseUrl(); ?>/<?php echo $this->controlador; ?>">
          <i class="fas fa-fw <?php echo $this->icono; ?>"></i>
          <?php echo $this->controlador; ?></a></li>
      <li class="breadcrumb-item active text-capitalize" aria-current="page">
        <?php echo $this->accion; ?></li>
    </ol>
  </nav>

</div>

<div class="row">
  <div class="col-md-3 col-sm-6 col-12">
    <!-- small box -->
    <div class="small-box bg-primary text-white ">
      <div class="inner">
        <h3><?php echo $this->cuenta_pacientes; ?></h3>

        <p>Pacientes internos</p>

      </div>
      <div class="icon">
        <i class="fas fa-user-tag "></i>
      </div>

      <a href="<?php echo $this->baseUrl();?>/listar_paciente" class="small-box-footer">Mas info <i
          class="fas fa-arrow-circle-right"></i></a>
    </div>
  </div>
  <div class="col-md-3 col-sm-6 col-12">
    <!-- small box -->
    <div class="small-box bg-secondary text-white ">
      <div class="inner">
        <h3><?php echo $this->cuenta_camas_disp; ?><sup style="font-size: 20px">%</sup></h3>

        <p>Camas disponibles</p>

      </div>
      <div class="icon">
        <i class="fas fa-bed "></i>
      </div>

      <a href="<?php echo $this->baseUrl();?>/camas?op=Disponible" class="small-box-footer">Mas info <i
          class="fas fa-arrow-circle-right"></i></a>
    </div>
  </div>
  <div class="col-md-3 col-sm-6 col-12">
    <!-- small box -->
    <div class="small-box bg-danger text-white ">
      <div class="inner">
        <h3><?php echo $this->cuenta_camas_ocup; ?><sup style="font-size: 20px">%</sup></h3>

        <p>Camas ocupadas</p>

      </div>
      <div class="icon">
        <i class="fas fa-bed "></i>
      </div>

      <a href="<?php echo $this->baseUrl();?>/camas?op=Ocupada" class="small-box-footer">Mas info <i
          class="fas fa-arrow-circle-right"></i></a>
    </div>
  </div>
  <div class="col-md-3 col-sm-6 col-12">
    <!-- small box -->
    <div class="small-box bg-warning text-dark ">
      <div class="inner">
        <h3><?php echo $this->cuenta_camas_desinf; ?><sup style="font-size: 20px">%</sup></h3>

        <p>En desinfeccion</p>

      </div>
      <div class="icon">
        <i class="fas fa-bed "></i>
      </div>

      <a href="<?php echo $this->baseUrl();?>/camas?op=Desinfeccion" class="small-box-footer">Mas info <i
          class="fas fa-arrow-circle-right"></i></a>
    </div>
  </div>

</div>

<div class="row">
  <div class="col-lg-9 ">
    <div class="card  shadow mb-4  ">
      <!-- Card Header - Dropdown -->
      <div class="card-header d-flex flex-row align-items-center justify-content-between">
        <h6 class="m-0 font-weight-bold text-primary">Camas por especialidad</h6>
        <div class="dropdown no-arrow">
          <a class="dropdown-toggle px-4" href="#" onclick="camasPorServicio();">
            <i class="fas fa-sync-alt fa-sm fa-fw text-gray-400"></i>
          </a>
          <!-- <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown"
            aria-haspopup="true" aria-expanded="false">
            <i class="fas fa-filter fa-sm fa-fw text-gray-400"></i>
          </a>
          <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
            <div class="dropdown-header">Opciones:</div>
            <a class="dropdown-item" href="#" onclick="camasPorServicio(0);">Disponibles</a>
            <a class="dropdown-item" href="#" onclick="camasPorServicio(1);">Ocupadas</a>
            <a class="dropdown-item" href="#" onclick="camasPorServicio(2);">Desinfeccion</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#" onclick="camasPorServicio();">Todas</a>

          </div> -->
        </div>
      </div>
      <div class="card-body pt-0">
        <canvas id="myChart" width="120" height="50"></canvas>

      </div>
    </div>


  </div>
  
  <div class="col-lg-3">
    <div class="row">
      <div class="col-12">
        <!-- small box -->
        <div class="small-box bg-success text-white ">
          <div class="inner">
            <h3><?php echo $this->cuenta_usuarios ?></h3>
      
            <p>Usuarios</p>
      
          </div>
          <div class="icon">
            <i class="fas fa-users "></i>
          </div>
      
          <a href="<?php echo $this->baseUrl();?>/listar_usuarios" class="small-box-footer">Mas info <i
              class="fas fa-arrow-circle-right"></i></a>
        </div>
      </div>

    </div>
    <div class="row">
      <div class="col-sm-12 mb-4">
        <div class="card  shadow  ">
          <!-- Card Header - Dropdown -->
          <div class="card-header d-flex flex-row align-items-center justify-content-between">
            <h6 class="m-0 font-weight-bold text-primary">Camas</h6>
            <div class="dropdown no-arrow">
              <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown"
                aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
              </a>
              <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in"
                aria-labelledby="dropdownMenuLink">
                <div class="dropdown-header">Dropdown Header:</div>
                <a class="dropdown-item" href="#">Action</a>
                <a class="dropdown-item" href="#">Another action</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#">Something else here</a>
              </div>
            </div>
          </div>
          <!-- Card Body -->
          <div class="card-body ">
            <canvas id="myPieChart"></canvas>
          </div>
        </div>
      </div>

    </div>


  </div>

</div>

<div class="row">
  <div class="col-xl-12 ">
    <div class="card shadow mb-4  ">
      <!-- Card Header - Dropdown -->
      <div class="card-header d-flex flex-row align-items-center justify-content-between">
        <h6 class="m-0 font-weight-bold text-primary">Mapa de pacientes y camas</h6>
        <div class="dropdown no-arrow">
          <a class="dropdown-toggle px-4" href="#" onclick="mapaDeCamas(0);">
            <i class="fas fa-sync-alt fa-sm fa-fw text-gray-400"></i>
          </a>
          <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown"
            aria-haspopup="true" aria-expanded="false">
            <i class="fas fa-filter fa-sm fa-fw text-gray-400"></i>
          </a>
          <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in " aria-labelledby="dropdownMenuLink">
            <div class="dropdown-header pl-4">Fecha:</div>

            <div class="dropdown-divider"></div>
            <a class="dropdown-item text-xxs pl-4" href="#" onclick="mapaDeCamas(0);">TODOS</a>

          </div>
        </div>
      </div>
      <div class="card-body divTarjeta text-xxs">
        <div id="data_MapaCamas"  >
        </div>
      </div>
      <div class="card-footer">
        <?php $obj = new Application_Model_DbTable_Especialidades();
              $datos = $obj->listar();
              if(isset($datos)): 
                foreach ($datos as $item): ?>
        <button type="button" class="btn btn-<?php echo $item->especialidad_color ?> btn-xs "
          onclick="mapaDeCamas('<?php echo $item->especialidad_id ?>');">
          <small><?php echo $item->especialidad_nombre ?></small>
        </button>
        <?php   endforeach;
               endif; ?>
        <button type="button" class="btn btn-light btn-xs" onclick="mapaDeCamas(0);">
          <small>TODOS</small></button>
      </div>
    </div>

  </div>
</div>

