

<div class="card  shadow mb-4">
   <div class="card-header  py-3 d-flex justify-content-between">
      <h4 class="m-0 font-weight-bold text-primary"><?php echo $this->titulo;?></h4>
   </div>
   <div class="card-body">
      <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Neque quos adipisci velit laborum excepturi earum sit alias ab libero illum reprehenderit, doloremque, fugit, quo corporis fuga nulla. Vero, quaerat at.</p>
      
   </div>
</div>