
<!-- Page Heading -->
<div class="d-flex justify-content-between">
          <h1 class="h3 mb-2 text-gray-800 text-capitalize"><?php echo $this->controlador;?>
          <small class="text-gray-400 text-capitalize"><?php echo $this->accion;?></small></h1>
            <ol class="breadcrumb bg-light">
              <li class="breadcrumb-item"><a href="<?php echo $this->baseUrl; ?>">
              Inicio</a></li>
              <li class="breadcrumb-item text-capitalize"><a href="#"><?php echo $this->controlador;?></a></li>
              <li class="breadcrumb-item active text-capitalize" aria-current="page"><?php echo $this->accion;?></li>
            </ol>
        </div>
<div class="card  shadow mb-4">
   <div class="card-header  py-3 d-flex justify-content-between">
      <h4 class="m-0 font-weight-bold text-primary"><?php echo $this->titulo;?></h4>
   </div>
   <div class="card-body">
      <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Neque quos adipisci velit laborum excepturi earum sit alias ab libero illum reprehenderit, doloremque, fugit, quo corporis fuga nulla. Vero, quaerat at.</p>
   </div>
</div>