<!-- DataTales Example -->
<div class="card border-left-primary">
    <div class="card-header bg-light d-flex justify-content-between align-middle pb-0">
        <h4 class="h4 text-capitalize text-dark"><?php echo $this->controlador; ?>
            <i class="fas fa-fw <?php echo $this->icono; ?> text-dark"></i></h4>
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb bg-transparent  text-xxs p-0 ">
                    <li class="breadcrumb-item"><a href="<?php echo $this->baseUrl(); ?>/panel_de_control">
                        <i class="fas fa-home "></i>Inicio</a></li>
                    <li class="breadcrumb-item text-capitalize">
                        <a href="<?php echo $this->baseUrl(); ?>/<?php echo $this->controlador; ?>">
                            <i class="fas fa-fw <?php echo $this->icono; ?>"></i>
                            <?php echo $this->controlador; ?></a></li>
                    <li class="breadcrumb-item active text-capitalize" aria-current="page">
                        <?php echo $this->accion; ?></li>
                </ol>
            </nav>      
        
    </div>
    <div class="card-body">
        <div class="d-flex justify-content-between pb-2">
            <button type="button" onclick="agregarModal()" class="btn btn-success btn-icon-split btn-sm">
                <span class="icon text-white-50"><i class="fas fa-plus"></i></span><span class="text">Agregar</span>
            </button>
            <div class="text-center align-content-center " id="exportButtons"></div> 
            
        </div>
        <div id="data_Table" class="table-responsive text-xs">
            <?php echo $this->data; ?>
        </div>
    </div>
</div>

<!-- formulario Modal-->
<div class="modal fade" id="formModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
    aria-hidden="true">
    <div class="modal-dialog modal-sm" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title text-primary" id="exampleModalLabel"></h5>
                <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <form class="needs-validation" method="post" id="formPisos" name="formPisos" novalidate>
                <div class="modal-body">
                    <input type="hidden" id="piso_id" name="piso_id">
                    <?php echo $this->data_area;?>
                    <div class="form-group">
                        <label for="nombre_piso">Nombre del piso:</label>
                        <input type="text" id="nombre_piso" class="form-control " name="nombre_piso" required autocomplete="off" >
                        <div class="valid-feedback">
                        </div>
                        <div class="invalid-feedback">
                            Este campo es necesario.
                        </div>
                    </div>
                
                </div>
                <div class="modal-footer d-flex justify-content-between">
                    <button class="btn btn-danger" type="button" data-dismiss="modal">Cancelar</button>
                    <div id="accionForm">                
                    </div>
                </div>
            </form>
            
        </div>
    </div>
</div>