<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">
  <title>PGCAM - Login</title>
  <!-- Custom fonts for this template-->
  <link href="/zend/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
  <link href="/zend/vendor/sweetalert2/css/sweetalert2.min.css" rel="stylesheet" type="text/css">

  <!-- Custom styles for this template-->
  <link href="<?php echo $this->baseUrl; ?>/assets/css/sb-admin-2.min.css" rel="stylesheet">
  <script src="/zend/vendor/sweetalert2/js/sweetalert2.min.js"></script>

</head>

<body id="page-top" >

  <div class="container animated--grow-in">

    <!-- Outer Row -->
    <div class="row justify-content-center py-auto">

      <div class="col-xl-10 col-lg-12 col-md-9">

        <div class="card o-hidden border-0 shadow-lg my-2">
          <div class="card-body p-0">
            <!-- Nested Row within Card Body -->
            <div class="row">
              <div class="col-lg-6 ">
				  		<img class="img-fluid py-5 px-2" src="<?php echo $this->baseUrl; ?>/assets/img/login.svg" alt="Login">
				  </div>
              <div class="col-lg-6 p-4">
                  <div class="text-center">
                    <h1 class="h2 text-gray-900 mb-4">Bienvenido!</h1>
                  </div>
                  <form class="user needs-validation" id="login" name="login" action="" method="post" novalidate>
                    <div class="form-group">
                      <input type="email" autofocus class="form-control form-control-user" id="email" name="email"
							 aria-describedby="emailHelp" required placeholder="Ingrese su email..." autocomplete="off"
                      value="<?php  echo $this->usuario_value; ?>">
                        <div class="valid-feedback">
                        </div>
                        <div class="invalid-feedback">
                            Por favor ingrese un correo electronico valido.
                        </div>
                    </div>
                    <div class="form-group">
                      <input type="password" class="form-control form-control-user" name="password"
							 id="password" required placeholder="Ingrese su contraseña..." autocomplete="off"
                             value="<?php  echo $this->clave_value; ?>">
                        <div class="valid-feedback">
                        </div>
                        <div class="invalid-feedback">
                            Debe ingresar su contraseña.
                        </div>
                    </div>
                    <div class="form-group">
                      <div class="custom-control custom-checkbox small">
                        <input type="checkbox" class="custom-control-input" id="customCheck">
                        <label class="custom-control-label" for="customCheck">Recordarme</label>
                      </div>
                    </div>
                      <?php if (!empty($this->message))
                                echo $this->message; ?>
                      <button type="submit" onclick="SendFormLogin(event);" class="btn btn-primary btn-user btn-block">
                          Ingresar
                      </button>
                  </form>

                  <hr>
                  <div class="text-center">
                    <button class="btn btn-link btn-sm" onclick="recuperarClave()" >Olvido su contraseña?</button>
                  </div>
                  <div class="text-center">
                    <a class="small" href="<?php echo $this->url(array('controller' => 'auth', 'action' => 'register')); ?>">Crear una cuenta!</a>
                  </div>
              </div>

            </div>
              <!-- Footer -->
              <footer class="sticky-footer  shadow">
                  <div class="container my-auto d-flex justify-content-between">
                      <div class="copyright text-center my-auto">
                          <span><strong><a href="https://www.ups.edu.ec/" target="_blank">Universidad Politecnica Salesiana</a> &copy; <?php echo date("Y");?></strong></span>
                      </div>
                      <div class="copyright text-center my-auto">
                          <span>Version <strong>1.0.0</strong></span>
                      </div>
                  </div>
              </footer>
              <!-- End of Footer -->
          </div>
        </div>

      </div>


    </div>


  </div>

  <!-- Bootstrap core JavaScript-->
  <script src="/zend/vendor/jquery/jquery.min.js"></script>
  <script src="/zend/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

  <!-- Core plugin JavaScript-->
  <script src="/zend/vendor/jquery-easing/jquery.easing.min.js"></script>

  <!-- Custom scripts for all pages-->
  <script src="<?php echo $this->baseUrl; ?>/assets/js/sb-admin-2.min.js"></script>
  <script src="<?php echo $this->baseUrl; ?>/functions/auth.js"></script>
  <input type="hidden" name="dir" id="dir" readonly="readonly"  value="<?php echo $this->baseUrl; ?>">
  <script >
      // Example starter JavaScript for disabling form submissions if there are invalid fields
      (function() {
          'use strict';
          window.addEventListener('load', function() {
              // Fetch all the forms we want to apply custom Bootstrap validation styles to
              var forms = document.getElementsByClassName('needs-validation');
              // Loop over them and prevent submission
              var validation = Array.prototype.filter.call(forms, function(form) {
                  form.addEventListener('submit', function(event) {
                      if (form.checkValidity() === false) {
                          event.preventDefault();
                          event.stopPropagation();
                      }
                      form.classList.add('was-validated');
                  }, false);
              });
          }, false);
      })();
  </script>

</body>

</html>
