<!-- Outer Row -->

<div class="card-body ">
  <!-- Nested Row within Card Body -->
  <div class="row ">
    <div class="col-lg-6 ">
      <img class="card-img-top h-100" src="<?php echo $this->baseUrl(); ?>/assets/img/login.svg" alt="Login">
    </div>
    <div class="col-lg-6 h-100">
      <div class="pt-3">
        <div class="text-center">
          <h1 class="h1 text-gray-900 mb-4 ">Iniciar Sesión!</h1>
        </div>
        <form class="needs-validation" id="login" name="login"  method="post" novalidate>
          <div class="form-group input-group">
            <div class="input-group-prepend">
              <span class="input-group-text "><i class="far fa-envelope "></i></span>
                </div>
                  <input type="email" autofocus class="form-control rounded-right " id="email" name="email" 
                  required placeholder="Ingrese su correo electronico..." autocomplete="off" data-toggle="tooltip"
                  data-placement="bottom" title="ejemplo@correo.com" 
                  pattern="[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,4}$">
        
                  <div class="valid-feedback"></div>
                  <div class="invalid-feedback">
                    Por favor ingrese un correo electronico valido.
                  </div>
            </div>
            <div class="form-group input-group">
              <div class="input-group-prepend">
                <span class="input-group-text "><i class="fas fa-key "></i></span>
              </div>
              <input type="password" class="form-control  border-right-0" name="password" id="password" required
                placeholder="Ingrese su contraseña..." autocomplete="off">
              <div class="input-group-append">
                <span id="show_password" class="input-group-text  rounded-right  border-left-0" data-toggle="tooltip" data-placement="right"
                  title="Mostrar/Ocultar" onclick="mostrarPassword()">
                  <i class="far fa-eye-slash icon text-primary"></i>
                </span>
              </div>
              <div class="valid-feedback">
              </div>
              <div class="invalid-feedback">
                Debe ingresar su contraseña.
              </div>
            </div>
            <!-- <div class="form-group">
                              <div class="custom-control custom-checkbox small">
                                <input type="checkbox" class="custom-control-input" id="customCheck">
                                <label class="custom-control-label" for="customCheck">Recordarme</label>
                              </div>
                            </div> -->
            
            <?php if (!empty($this->message))
                     echo $this->message; ?>
        
            <button type="submit" onclick="SendFormLogin(event);" class="btn btn-primary btn-block">
              <strong>Ingresar</strong>
            </button>
        </form>
        
        <hr>
        <div class="d-flex justify-content-between text-center">
          <button class="btn btn-link btn-sm" title="Haga click si olvidó su contraseña" data-toggle="modal"
            data-target="#exampleModal">Olvido su
            contraseña?</button>
          <a class="btn btn-link btn-sm" data-toggle="tooltip" data-placement="bottom"
            title="Haga click para crear una nueva cuenta" href="<?php echo $this->baseUrl();?>/nueva_cuenta">Crear una
            cuenta!</a>
            
        </div>
        <div class="alert alert-warning text py-1">
          <h6>DEMO</h6>
          <span>Usuario: admin@admin.com</span><br>
          <span>Contraseña: 123456</span>
        </div>
      </div>

    </div>

  </div>

</div>