<div class="card-body">
  <!-- Nested Row within Card Body -->
  <div class="row ">
    <div class="col-lg-5  ">
      <img class="card-img-top h-100 " src="<?php echo $this->baseUrl(); ?>/assets/img/registro.svg" alt="Registro">
    </div>
    <div class="col-lg-7 h-100">
      <div class="text-center">
        <h1 class="h1 text-gray-900 mb-4">Crear una cuenta!</h1>
      </div>
      <form class=" needs-validation" method="post" id="register" name="register" novalidate >
        <div class="form-group row">
          <div class="col-sm-6 mb-3 mb-sm-0">
            <input type="text" autofocus class="form-control " name="nombre" id="nombre" autocomplete="off"
              placeholder="Nombre" required onkeyup="this.value = this.value.toUpperCase();"
              pattern="\D{1,50}">
            <div class="valid-feedback">
            </div>
            <div class="invalid-feedback">
              Formato inválido.
            </div>
          </div>
          <div class="col-sm-6">
            <input type="text" class="form-control " name="apellido" id="apellido" autocomplete="off"
              placeholder="Apellido" required onkeyup="this.value = this.value.toUpperCase();"
              pattern="\D{1,50}">
            <div class="valid-feedback">
            </div>
            <div class="invalid-feedback">
              Formato inválido.
            </div>
          </div>
        </div>
        <div class="form-group">
          <input type="email" class="form-control " name="email" id="email" autocomplete="off"
            placeholder="Direccion de correo" required onkeyup="this.value = this.value.toLowerCase();"
            pattern="[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,4}$">
          <div class="valid-feedback">
          </div>
          <div class="invalid-feedback">
            Por favor ingrese un correo electrónico válido.
          </div>
        </div>
        <div class="row">
          <div class="col-sm-6 mb-3 mb-sm-0">
            <div class="form-group input-group">
              <input type="password" class="form-control " name="clave1" id="clave1" autocomplete="off"
              placeholder="Contraseña" required minlength="6">
              
            <div class="valid-feedback">
            </div>
            <div class="invalid-feedback">
              Debe ingresar al menos 6 caracteres.
            </div>
            </div>
            
          </div>
          <div class="col-sm-6 mb-3 mb-sm-0">
            <div class="form-group input-group">
              <input type="password" class="form-control " name="clave2" id="clave2" autocomplete="off"
              placeholder="Repita su contraseña" required minlength="6">
              
            <div class="valid-feedback">
            </div>
            <div class="invalid-feedback">
              Debe ingresar al menos 6 caracteres.
            </div>
            </div>

            
          </div>
        </div>
        <div id="clave_igual"></div>
        <div class="form-group">
          <?php echo $this->getPerfil(); ?>

        </div>
        <button type="submit" onclick="SendFormRegister();" class="btn btn-primary btn-block">
          <strong>Registrar cuenta</strong>
        </button>
      </form>
      <hr>
      <div class="text-center">
        <span class="text-gray-600">Ya posee una cuenta?</span>
        <a class="btn btn-link btn-sm"
          href="<?php echo $this->baseUrl();?>/iniciar_sesion">
          Clic aqui!</a>
      </div>
    </div>
  </div>

</div>