<div class="row">
    <div class="col-md-6">
      <div class="form-group">
        <label>Minimal</label>
        <select class="form-control select2" style="width: 100%;">
          <option selected="selected">Alabama</option>
          <option>Alaska</option>
          <option>California</option>
          <option>Delaware</option>
          <option>Tennessee</option>
          <option>Texas</option>
          <option>Washington</option>
        </select>
      </div>
      </div>
    </div>
          <!-- DataTales Example -->
          <div class="card  shadow mb-4">
            <div class="card-header  py-3 d-flex justify-content-between">
              <h4 class="m-0 font-weight-bold text-primary"><?php echo $this->titulo;?></h4>
              <button class="btn btn-success btn-sm" onclick="agregarModal()">
                  <i class="fa fa-plus"></i> Agregar
              </button>
            </div>
            <div class="card-body">
           
              <div id="data_Table" class="table-responsive">
                <?php echo $this->data; ?>
              </div>
            </div>
          </div>
<!-- formulario Modal-->

<div class="modal fade" id="formModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
     aria-hidden="true">
    <div class="modal-dialog modal-sm" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title text-primary" id="exampleModalLabel"></h5>
                <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <div class="modal-body">
                <input type="hidden" id="cama_id" name="cama_id">
                    <?php echo $this->data_habitaciones;?>
                    <div  class="form-group">
                        <label for="nombre_cama">Nombre de la cama:</label>
                        <input type="text"
                        id="nombre_cama"
                        class="form-control "
                        name="nombre_cama"
                        required autocomplete="off" onkeyup="validar()">
                        <small  id="nombreHelp" ></small>
                    </div>
                    <hr>
                    <div class="d-flex justify-content-between">
                        <button class="btn btn-danger" type="button" data-dismiss="modal">Cancelar</button>
                        <div id="accionForm">

                        </div>
                    </div>
            </div>
        </div>
    </div>
</div>
<script src="<?php echo $this->baseUrl; ?>/functions/camas.js"></script>
<script>
    $(document).ready(function() {
      //Initialize Select2 Elements
      $('.select2').select2();
  
      
  
    });
  </script>