<!-- DataTales Example -->
<div class="card border-left-primary">
    <div class="card-header bg-light d-flex justify-content-between align-middle pb-0">
        <h4 class="h4 text-capitalize text-dark"><?php echo $this->controlador; ?>
            <i class="fas fa-fw <?php echo $this->icono; ?> text-dark"></i></h4>

        <nav aria-label="breadcrumb">
            <ol class="breadcrumb bg-transparent  text-xxs p-0 ">
                <li class="breadcrumb-item"><a href="<?php echo $this->baseUrl(); ?>/panel_de_control">
                        <i class="fas fa-home "></i>Inicio</a></li>
                <li class="breadcrumb-item text-capitalize">
                    <a href="<?php echo $this->baseUrl(); ?>/<?php echo $this->controlador; ?>">
                        <i class="fas fa-fw <?php echo $this->icono; ?>"></i>
                        <?php echo $this->controlador; ?></a></li>
                <li class="breadcrumb-item active text-capitalize" aria-current="page">
                    <?php echo $this->accion; ?></li>
            </ol>
        </nav>


    </div>
    <div class="card-body">
        <input type="hidden" name="campoBusqueda" id="campoBusqueda"
            value="<?php if (isset($_GET['op'])) echo $_GET['op']; ?>">
        <div class="d-flex justify-content-between pb-2">
            <div class="text-center align-content-center" id="exportButtons"></div>
            <button type="button" onclick="agregarModal()" class="btn btn-success btn-icon-split btn-sm">
                <span class="icon text-white-50"><i class="fas fa-plus"></i></span><span class="text">Agregar</span>
            </button>
            

        </div>
        <div id="data_Table" class="table-responsive text-xs">
            <?php echo $this->data; ?>
        </div>
    </div>
</div>
<div class="row py-5">
    <div class="col-xl-6 col-md-12">
        <div class="card shadow mb-4 ">
            <!-- Card Header - Dropdown -->
            <div class="card-header d-flex flex-row align-items-center justify-content-between">
                <h6 class="m-0 font-weight-bold text-primary">Camas</h6>
                <div class="dropdown no-arrow">
                    <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown"
                        aria-haspopup="true" aria-expanded="false">
                        <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in"
                        aria-labelledby="dropdownMenuLink">
                        <div class="dropdown-header">Dropdown Header:</div>
                        <a class="dropdown-item" href="#">Action</a>
                        <a class="dropdown-item" href="#">Another action</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="#">Something else here</a>
                    </div>
                </div>
            </div>
            <!-- Card Body -->
            <div class="card-body ">
                <canvas id="myPieChart" width="45" height="250"></canvas>
            </div>
        </div>

    </div>
</div>
<!-- formulario Modal-->

<div class="modal fade" id="formModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
    aria-hidden="true">
    <div class="modal-dialog " role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title text-primary" id="exampleModalLabel"></h5>
                <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <form class="needs-validation" method="post" id="formCamas" name="formCamas" novalidate>
                <div class="modal-body">
                    <input type="hidden" id="cama_id" name="cama_id">

                    <div class="row">
                        <div class="col-sm-6">
                            <?php echo $this->data_habitaciones;?>
                        </div>
                        <div class="col-sm-6">
                            <div class="form-group">
                                <label for="nombre_cama">Nombre de la cama:</label>
                                <input type="text" id="nombre_cama" class="form-control " name="nombre_cama" required autocomplete="off">
                                <div class="valid-feedback">
                                </div>
                                <div class="invalid-feedback">
                                    Este campo es necesario.
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-8">
                            <?php echo $this->data_tipo;?>
                        </div>
                        <div class="col-sm-4">
                            <?php echo $this->data_estado_cama;?>
                        </div>
                    </div>           
                </div>
                <div class="modal-footer d-flex justify-content-between">
                    <button class="btn btn-danger" type="button" data-dismiss="modal">Cancelar</button>
                    <div id="accionForm">

                    </div>
                </div>
            </form>

        </div>
    </div>
</div>