<script>
    $(function () {
        $('#dataTable').DataTable()
    });
</script>
        <!-- Page Heading -->
        <div class="d-flex justify-content-between">
          <h1 class="h3 mb-2 text-gray-800 text-capitalize"><?php echo $this->controlador;?>
          <small class="text-gray-400 text-capitalize"><?php echo $this->accion;?></small></h1>
            <ol class="breadcrumb bg-light">
              <li class="breadcrumb-item"><a href="<?php echo $this->baseUrl; ?>">
              Inicio</a></li>
              <li class="breadcrumb-item text-capitalize"><a href="#"><?php echo $this->controlador;?></a></li>
              <li class="breadcrumb-item active text-capitalize" aria-current="page"><?php echo $this->accion;?></li>
            </ol>
        </div>
          <!-- DataTales Example -->
          <div class="card  shadow mb-4">
            <div class="card-header  py-3 d-flex justify-content-between">
              <h4 class="m-0 font-weight-bold text-primary"><?php echo $this->titulo;?></h4>
              <button class="btn btn-success btn-sm">
                  <i class="fa fa-plus"></i> Agregar
              </button>
            </div>
            <div class="card-body">
           
              <div class="table-responsive">
              <?php if (empty($this->data)) { ?>
                        <div class="alert alert-danger" role="alert">
                            No se encontraron resultados</div>
                    <?php } else { ?>
                <table class="table table-sm" id="dataTable" width="100%" >
                  <thead>
                    <tr>
                      <th class="text-primary">ID</th>
                      <th class="text-primary">DESCRIPCION</th>
                      <th class="text-primary">HABITACION</th>
                      <th class="text-primary">ESPECIALIDAD</th>
                      <th class="text-primary">PISO</th>
                      <th class="text-primary">AREA</th>
                      <th class="text-primary">ESTADO</th>
                      <th class="text-primary ">ACCION</th>
                    </tr>
                  </thead>
                  <tbody>
                    <tr>
                    <?php foreach ($this->data as $item): ?>
                      <td><?php echo $item->cama_id ?></td>
                      <td>CAMA - <?php echo $item->cama_nombre ?></td>
                      <td><?php echo $item->habitacion_nombre ?></td>
                      <td><?php echo $item->especialidad_nombre ?></td>
                      <td><?php echo $item->piso_nombre ?></td>
                      <td><?php echo $item->area_nombre ?></td>
                      <td><?php echo $item->cama_estado ?></td>
                      <td >
                            <button class="btn  btn-sm ">
                              <i class="fa fa-eye text-primary"></i>
                            </button>
                            <button class="btn  btn-sm ">
                              <i class="fa fa-edit text-warning"></i>
                            </button>
                            <button class="btn  btn-sm ">
                              <i class="fa fa-trash text-danger"></i>
                            </button>
                      </td>
                    </tr>
                    <?php endforeach;
                            } ?>
                  </tbody>
                </table>
              </div>
            </div>
          </div>
