<div class="card border-left-primary">
	<div class="card-header bg-light d-flex justify-content-between align-middle pb-0">
		<h4 class="h4 text-capitalize text-dark"><?php echo $this->controlador; ?>
			 <i class="fas fa-fw <?php echo $this->icono; ?> text-dark"></i></h4>
			 <nav aria-label="breadcrumb">
				  <ol class="breadcrumb bg-transparent  text-xxs p-0 ">
						<li class="breadcrumb-item"><a href="<?php echo $this->baseUrl(); ?>/panel_de_control">
							 <i class="fas fa-home "></i>Inicio</a></li>
						<li class="breadcrumb-item text-capitalize">
							 <a href="<?php echo $this->baseUrl(); ?>/<?php echo $this->controlador; ?>">
								  <i class="fas fa-fw <?php echo $this->icono; ?>"></i>
								  <?php echo $this->controlador; ?></a></li>
						<li class="breadcrumb-item active text-capitalize" aria-current="page">
							 <?php echo $this->accion; ?></li>
				  </ol>
			 </nav>      
		
  </div>
	<div class="card-body">
		<div class="row pb-2">
			<div class="col-sm-4"></div>
			<div class="col-sm-4">
				<div class="btn-group d-flex justify-content-start" role="group" aria-label="Basic example">
					<a class="btn btn-outline-primary <?php echo $this->setActive('usuarios','index'); ?> btn-icon-split btn-sm"
						href="<?php echo $this->baseUrl();?>/listar_usuarios">
						<span class="text">Usuarios</span></a>
					<a class="btn btn-outline-primary <?php echo $this->setActive('usuarios','perfiles'); ?> btn-icon-split btn-sm"
						href="<?php echo $this->baseUrl();?>/listar_perfiles">
						<span class="text">Perfiles</span></a>

				</div>
			</div>
			<div class="col-sm-4"></div>
		</div>
		<div class="row">
			<div class="col-sm-12">
				<div class="d-flex justify-content-between pb-2">
					<div class="text-center align-content-center " id="exportButtons"></div>
					<button type="button" onclick="agregarModalU()" class="btn btn-success btn-icon-split btn-sm">
						<span class="icon text-white-50"><i class="fas fa-plus"></i></span><span class="text">Agregar</span>
				  </button>
					
					
			  </div>
				<div id="data_Table" class="table-responsive text-xs">
					<?php echo $this->data_usuarios; ?>
				</div>
			</div>
		</div>
	</div>
</div>
<!-- formulario Modal-->
<div class="modal fade" id="formModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
	aria-hidden="true">
	<div class="modal-dialog " role="document">
		<div class="modal-content">
			<div class="modal-header">
				<h5 class="modal-title text-primary" id="exampleModalLabel"></h5>
				<button class="close" type="button" data-dismiss="modal" aria-label="Close">
					<span aria-hidden="true">×</span>
				</button>
			</div>
			<form class="user needs-validation" method="post" id="register" name="register" novalidate>

				<div class="modal-body">
					<input type="hidden" id="usuario_id" name="usuario_id">
					<div class="row">
						<div class="col-sm-6">
							<div class="form-group">
								<label for="nombres">Nombres:</label>
								<input type="text" id="nombres" class="form-control " name="nombres" placeholder="Nombres..."
									required autocomplete="off"
									onkeyup="this.value = this.value.toUpperCase();"
									pattern="\D{1,50}">
								<div class="valid-feedback">
								</div>
								<div class="invalid-feedback">
									Este campo es necesario.
								</div>
							</div>
						</div>
						<div class="col-sm-6">
							<div class="form-group">
								<label for="apellidos">Apellidos:</label>
								<input type="text" id="apellidos" class="form-control " name="apellidos"
									placeholder="Apellidos..." required autocomplete="off"
									onkeyup="this.value = this.value.toUpperCase();"
									pattern="\D{1,50}">
								<div class="valid-feedback">
								</div>
								<div class="invalid-feedback">
									Este campo es necesario.
								</div>
							</div>
						</div>
					</div>
					<div class="row">
						<div class="col-sm-12">
							<div class="form-group">
								<label for="correo">Correo electronico:</label>
								<input type="email" id="correo" class="form-control input-group-sm" name="correo"
									placeholder="ejemplo@ejemplo.com" required autocomplete="off"
									onkeyup="this.value = this.value.toLowerCase();"
									pattern="[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,4}$">
								<div class="valid-feedback">
								</div>
								<div class="invalid-feedback">
									Por favor ingrese un correo electronico valido.
								</div>
							</div>
						</div>
					</div>
					<div class="row">
						<div class="col-sm-6">
							<?php echo $this->data_perfiles;?>

						</div>
						<div class="col-sm-6">
							<?php echo $this->data_estado;?>

						</div>
					</div>
					<small id="claveHelp" class="form-text text-muted">Contraseña por defecto para nuevos usuarios: HGOPNA2020</small>
					<div id="clave_igual"></div>

					
				</div>
				<div class="modal-footer d-flex justify-content-between ">
					<button class="btn btn-danger" type="button" data-dismiss="modal">Cancelar</button>
					<div id="accionForm">

					</div>
				</div>
			</form>

		</div>
	</div>
</div>