<div class="card  shadow ">
	<div class="card-header d-flex justify-content-between">
		 <h5 class="m-0 font-weight-bold text-primary"><?php echo $this->titulo; ?></h5>
		 <button type="button"  onclick="agregarModal()" 
		 class="btn btn-success btn-sm" >
			  <i class="fa fa-plus"></i> Agregar
		 </button> 
		 
	</div>
	<div class="card-body">
				<div class="row">
					<div class="col-sm-12">
						<div class="table-responsive">
							<?php echo $this->data_perfiles; ?>
					
						</div>
					</div>
				</div>
	</div>
</div>