<!-- Footer -->
<footer class="sticky-footer bg-white shadow ">
   <div class="container my-auto d-flex justify-content-between">
     <div class="copyright text-center my-auto">
       <span><strong>Powered by <a href="https://www.ups.edu.ec/" target="_blank">
       Universidad Politecnica Salesiana<sup >EC</sup></a> &copy; <?php echo date("Y");?>
     </strong></span>
     </div>
     
     <div class="copyright text-center my-auto">
       <!-- <span class="mx-2">Powered by <a target="_blank" 
        href="https://framework.zend.com/" class="text-success">Zend Framework</a></span> -->
       |<span class="mx-2"> Version <strong>1.0</strong></span>
     </div>
     <!-- <img src="http://framework.zend.com/images/PoweredBy_ZF_4LightBG.png" /> -->
   </div>
 </footer>
 <!-- End of Footer -->