<!-- Footer -->
<footer class="sticky-footer   ">
  <div class="container my-auto d-flex justify-content-between">
    <div class="copyright text-center my-auto">
      <strong><a href="https://www.ups.edu.ec/" target="_blank">
          Universidad Politécnica Salesiana</a> &copy; <?php echo date("Y");?>
      </strong>
    </div>
    <div class="copyright text-center my-auto">
      <?php if($this->controlador == 'auth'){ ?>
      <!-- <a class="mx-1" href=""><i class="fab fa-facebook text-primary"></i></a>
        <a class="mx-1" href="https://api.whatsapp.com/send?phone=+5930983078906&text=Necesito%20su%20ayuda">
          <i class="fab fa-whatsapp text-success"></i></a> -->
      <a class="mx-1" data-toggle="tooltip" data-placement="bottom" title="Repositorio en GitHub"
       href="https://github.com/juanpv1609/zend.git" target="_blank">
        <i class="fab fa-github text-dark"></i></a>
      <?php } ?> Versión <strong>1.0</strong>

    </div>
    <!-- <img src="http://framework.zend.com/images/PoweredBy_ZF_4LightBG.png" /> -->
  </div>
</footer>
<!-- End of Footer -->