<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<meta name="description" content="Plataforma de Gestion de camas hospitalarias">
<meta name="author" content="Juan Perugachi">

<title><?php echo 'PGCAM - '.$this->titulo; ?></title>
<!-- Custom fonts for this template-->
<link href="<?php echo $this->baseUrl(); ?>/assets/css/sb-admin-2.min.css" rel="stylesheet">
<link href="<?php echo $this->baseUrl(); ?>/assets/css/animate.css" rel="stylesheet">
<link href="<?php echo $this->baseUrl(); ?>/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">

<link href="<?php echo $this->baseUrl(); ?>/vendor/datatables/dataTables.bootstrap4.min.css" rel="stylesheet"
  type="text/css">
<link href="<?php echo $this->baseUrl(); ?>/vendor/datatables/buttons.bootstrap4.min.css" rel="stylesheet"
  type="text/css">
<link href="<?php echo $this->baseUrl(); ?>/vendor/datatables/fixedHeader.bootstrap4.min.css" rel="stylesheet"
  type="text/css">
<link href="<?php echo $this->baseUrl(); ?>/vendor/datatables/responsive.bootstrap4.min.css" rel="stylesheet"
  type="text/css">

<link href="<?php echo $this->baseUrl(); ?>/assets/fonts/fonts.css" rel="stylesheet" type="text/css">
<!-- Custom styles for this template-->

<link href="<?php echo $this->baseUrl(); ?>/vendor/select2/css/select2.css" rel="stylesheet">
<link href="<?php echo $this->baseUrl(); ?>/vendor/select2/css/select2-bootstrap.min.css" rel="stylesheet">
<!-- <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet"> -->
<link href="<?php echo $this->baseUrl(); ?>/vendor/sweetalert2/css/wordpress-admin.min.css" rel="stylesheet"
  type="text/css">
<link href="<?php echo $this->baseUrl(); ?>/vendor/bootstrap4-toggle/css/bootstrap4-toggle.min.css" rel="stylesheet">

<link rel="icon" type="image/vnd.microsoft.icon" href="<?php echo $this->baseUrl(); ?>/favicon.svg">