<div class="modal fade" id="formModal_password" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
     aria-hidden="true">
    <div class="modal-dialog modal-sm" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title text-primary" id="exampleModalLabel">Cambio de contraseña</h5>
                <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
				</div>
				<form class="user needs-validation" method="post" id="register" name="register" novalidate >
				
            <div class="modal-body">
					<div id="accionFormCambiaClave" style="display: none;">
						
						<div class="row">
	
							<div class="col-sm-12">
								<div  class="form-group">
									<input type="password"
									id="nueva_clave"
									class="form-control bg-white"
									name="nueva_clave"
									placeholder="Ingrese una nueva contraseña"
									required autocomplete="off"  minlength="6">
									<div class="valid-feedback">
									</div>
									<div class="invalid-feedback">
										Al menos 6 caracteres.
									</div>
							  </div>
							</div>
						</div>
						<div class="row">
	
							<div class="col-sm-12">
								<div  class="form-group">
									<input type="password"
									id="nueva_clave_2"
									class="form-control bg-white"
									name="nueva_clave_2"
									placeholder="Repita la nueva contraseña"
									required autocomplete="off" minlength="6" >
									<div class="valid-feedback">
									</div>
									<div class="invalid-feedback">
										Al menos 6 caracteres.
									</div>
									<div id="clave_igual"></div>

									<hr>
									<div class=" d-flex justify-content-between">
										<button class="btn btn-outline-danger" type="button" data-dismiss="modal">Cancelar</button>
										<button type="submit" class="btn btn-outline-success" onclick="ActualizaClaveUsuario()">Cambiar contraseña</button>
									</div>
							  </div>
							</div>
                  </div>
					</div>
				</div>
			</form>
				
        </div>
    </div>
</div>