<!-- Topbar -->
<nav class="navbar  navbar-expand bg-white navbar-white navbar-light text-sm shadow" >
   <!-- Sidebar Toggle (Topbar) -->
     
  <ul class="navbar-nav">
    <li class="nav-item">
     <button id="sidebarToggleTop" class="btn btn-circle border-0 ">
       <i class="fas fa-bars " aria-hidden="true"></i>
     </button>
    </li>
  </ul>          
   <!-- Topbar Search -->
   <form class="d-none d-sm-inline-block form-inline mr-auto ml-md-3  my-md-0 mw-100 navbar-search">
     <div class="input-group input-group-sm ">
       <input type="text" class="form-control " placeholder="Buscar..." aria-label="Search" aria-describedby="basic-addon2">
       <div class="input-group-append">
         <button class="btn btn-dark" type="button">
           <i class="fas fa-search fa-sm text-white"></i>
         </button>
       </div>
     </div>
   </form>
   <!-- <img class="img-fluid" src="<?php echo $this->baseUrl; ?>/assets/img/logo_msp_2019.png" 
     width="200" height="100" alt=""> -->
   <!-- Topbar Navbar -->
   <ul class="navbar-nav ml-auto">
     <!-- Nav Item - Search Dropdown (Visible Only XS) -->
     <li class="nav-item dropdown no-arrow d-sm-none">
       <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
         <i class="fas fa-search fa-fw "></i>
       </a>
       <!-- Dropdown - Messages -->
       <div class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in" aria-labelledby="searchDropdown">
         <form class="form-inline mr-auto w-100 navbar-search">
           <div class="input-group input-group-sm">
             <input type="text" class="form-control" placeholder="Buscar..." aria-label="Search" aria-describedby="basic-addon2">
             <div class="input-group-append">
               <button class="btn btn-dark" type="button">
                 <i class="fas fa-search fa-sm text-white"></i>
               </button>
             </div>
           </div>
         </form>
       </div>
         
      
     </li>
     <li class="nav-item">
      <a class="nav-link " href="#" >
        <i class="far fa-question-circle"></i>
        <!-- Counter - Alerts -->
      </a>
    </li>
     <!-- Nav Item - Alerts -->
     <li class="nav-item dropdown no-arrow">
       <a class="nav-link dropdown-toggle" href="#" id="alertsDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
         
         <i class="far fa-bell"></i>
         <span class="badge badge-danger navbar-badge">3+</span>
         <!-- Counter - Alerts -->
       </a>
       <!-- Dropdown - Alerts -->
       <div class="dropdown-list dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="alertsDropdown">
         <h6 class="dropdown-header">
           Alertas
         </h6>
         <a class="dropdown-item d-flex align-items-center" href="#">
           <div class="mr-1">
             <div class="icon-circle bg-primary">
               <i class="fas fa-file-alt text-white"></i>
             </div>
           </div>
           <div>
             <div class="small text-gray-500">December 12, 2019</div>
             <span class="font-weight-bold">A new monthly re</span>
           </div>
         </a>
         <a class="dropdown-item d-flex align-items-center" href="#">
           <div class="mr-1">
             <div class="icon-circle bg-success">
               <i class="fas fa-donate text-white"></i>
             </div>
           </div>
           <div>
             <div class="small text-gray-500">December 7, 2019</div>
             $290.29 has be
           </div>
         </a>
         <a class="dropdown-item d-flex align-items-center" href="#">
           <div class="mr-1">
             <div class="icon-circle bg-warning">
               <i class="fas fa-exclamation-triangle text-white"></i>
             </div>
           </div>
           <div>
             <div class="small text-gray-500">December 2, 2019</div>
             Spending Alert: We'v.
           </div>
         </a>
         <a class="dropdown-item text-center small text-gray-500" href="#">Show All Alerts</a>
       </div>
     </li>
     <!-- Nav Item - Messages -->
     <li class="nav-item dropdown no-arrow mr-4">
      <a class="nav-link dropdown-toggle" href="#" id="msgDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <i class="far fa-envelope"></i>
        <span class="badge badge-warning navbar-badge">7</span>
        <!-- Counter - Alerts -->
      </a>
      <!-- Dropdown - Alerts -->
      <div class="dropdown-list dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="msgDropdown">
        <h6 class="dropdown-header">
          Mensajes
        </h6>
        <a class="dropdown-item d-flex align-items-center" href="#">
          
          <div>
            <div class="small text-gray-500">December 12, 2019</div>
            <span class="font-weight-bold">A new monthly re</span>
          </div>
        </a>
        <a class="dropdown-item d-flex align-items-center" href="#">
          
          <div>
            <div class="small text-gray-500">December 7, 2019</div>
            $290.29 has be
          </div>
        </a>
        <a class="dropdown-item d-flex align-items-center" href="#">
          
          <div>
            <div class="small text-gray-500">December 2, 2019</div>
            Spending Alert: We'v.
          </div>
        </a>
        <a class="dropdown-item text-center small text-gray-500" href="#">Show All Messages</a>
      </div>
    </li>
     <!-- Nav Item - User Information -->
     <li class="nav-item dropdown no-arrow my-auto mx-1">
      <?php if($this->user) : 
            $obj = new Application_Model_DbTable_Usuario();
            $perfil = $obj->obtienePerfil($this->user->usu_id);
      ?>
       <a class=" dropdown-toggle btn btn-primary btn-circle btn-sm" 
       href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
       <span class="text-uppercase">
        <?php 
            echo substr($this->user->usu_nombres,0,1).substr($this->user->usu_apellidos,0,1); 
            else : ?>
            <a href="<?php echo $this->url(array('controller' => 'auth', 'action' => 'login')); ?>"  
              class="btn btn-outline-primary btn-sm">Iniciar Sesión</a>
              <?php  endif; ?>
            </span>        
             
       </a>
       <!-- Dropdown - User Information -->
       <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">
        
         <h6 class="dropdown-header">Mi cuenta</h6>
         <div class="d-flex justify-content-between ">
          <a class=" dropdown-toggle btn btn-primary btn-circle btn-lg ml-3" href="#">
          <span class="text-uppercase"><?php echo substr($this->user->usu_nombres,0,1).substr($this->user->usu_apellidos,0,1); ?></span>
          </a>
          <a class="dropdown-item" href="#">
            <strong><?php echo $this->escape($this->user->usu_nombres." ".$this->user->usu_apellidos); ?></strong><br>
            <span><?php  echo $this->escape($this->user->correo); ?> </span> 
            <br>
            <span><?php  echo $this->escape($perfil->perf_nombre); ?> </span>              
            </a>
         </div>
         <!-- Divider -->
   <hr class="sidebar-divider">
         <a class="dropdown-item" href="#">
           <i class="fas fa-cogs fa-sm fa-fw mr-2"></i>
           Configuracion
         </a>
         <button class="dropdown-item" onclick="logout()" >
           <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2"></i>
           Salir
         </button>
       </div>
     </li>
   </ul>
 </nav>
 <!-- End of Topbar -->