<!-- Topbar -->
<nav class="navbar  navbar-expand bg-white topbar navbar-light text-sm   border">
  <!-- Sidebar Toggle (Topbar) -->

  <ul class="navbar-nav">
    <li class="nav-item" data-toggle="tooltip" data-placement="bottom" title="Contraer / Expandir">
      <button id="sidebarToggleTop" class="btn btn-flat border-0 ">
        <i class="fas fa-bars " aria-hidden="true"></i>
      </button>
    </li>
  </ul>
  <!-- Topbar Search -->
  <form class="d-none d-sm-inline-block form-inline mr-auto ml-md-3  my-md-0 mw-100 navbar-search">
    <div class="input-group input-group-sm ">
      <input type="text" id="navBuscar" name="navBuscar"
        class="form-control border-0" placeholder="Buscar..." aria-label="Search"aria-describedby="basic-addon2"
        >
      <div class="input-group-append">
        <button class="btn btn-dark" type="button">
          <i class="fas fa-search fa-sm "></i>
        </button>
      </div>
    </div>
  </form>
  <!-- <img class="img-fluid" src="<?php echo $this->baseUrl; ?>/assets/img/logo_msp_2019.png" 
     width="200" height="100" alt=""> -->
  <!-- Topbar Navbar -->

  <ul class="navbar-nav ml-auto">
    <!-- Nav Item - Search Dropdown (Visible Only XS) -->
    <li class="nav-item dropdown no-arrow d-sm-none">
      <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button" data-toggle="dropdown"
        aria-haspopup="true" aria-expanded="false" >
        <i class="fas fa-search fa-fw text-secondary"></i>
      </a>
      <!-- Dropdown - search -->
      <div class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in" aria-labelledby="searchDropdown">
        <form class="form-inline mr-auto w-100 navbar-search">
          <div class="input-group input-group-sm">
            <input type="text" class="form-control" placeholder="Buscar..." aria-label="Search"
              aria-describedby="basic-addon2">
            <div class="input-group-append">
              <button class="btn btn-dark" type="button">
                <i class="fas fa-search fa-sm text-white"></i>
              </button>
            </div>
          </div>
        </form>
      </div>


    </li>
    <li class="nav-item dropdown no-arrow">
      <a class="nav-link dropdown-toggle"  href="#" id="calendar" role="button" data-toggle="dropdown"
        aria-haspopup="true" aria-expanded="false">
        <i class="fas fa-calendar-alt  mx-1"></i>

      </a>
      <div class="dropdown-list dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="calendar">

        <a class="dropdown-item d-flex align-items-center" href="#">
          <div class="mr-1">
            <div class="icon-circle bg-primary">
              <i class="fas fa-calendar-alt text-white"></i>
            </div>
          </div>
          <div>
            <span class="font-weight-bold"><?php setlocale(LC_TIME,"es_EC.UTF-8");
              date_default_timezone_set('America/Guayaquil'); ?>
              <span class="text-xs"><?php echo strftime("%A, %d de %B de %Y"); ?></span></span>
          </div>
        </a>

      </div>
    </li>
    <li class="nav-item " data-toggle="tooltip" data-placement="bottom" title="Manual de usuario">
      <a class="nav-link " href="#">
        <i class="far fa-question-circle "></i>
        <!-- Counter - Alerts -->
      </a>

    </li>
    <!-- Nav Item - Alerts -->
    <li class="nav-item dropdown no-arrow " data-toggle="tooltip" data-placement="bottom" title="Notificaciones">
      <a class="nav-link dropdown-toggle" href="#" id="alertsDropdown" role="button" data-toggle="dropdown"
        aria-haspopup="true" aria-expanded="false">

        <i class="far fa-bell"></i>
        <span class="badge badge-danger badge-counter">3</span>
        <!-- Counter - Alerts -->
      </a>
      <!-- Dropdown - Alerts -->
      <div class="dropdown-list dropdown-menu dropdown-menu-right shadow-lg animated--grow-in"
        aria-labelledby="alertsDropdown">
        <h6 class="dropdown-header">
          Alertas
        </h6>
        <a class="dropdown-item d-flex align-items-center" href="#">
          <div class="mr-1">
            <div class="icon-circle bg-primary">
              <i class="fas fa-file-alt text-white"></i>
            </div>
          </div>
          <div>
            <div class="small text-gray-500">December 12, 2019</div>
            <span class="font-weight-bold">A new monthly re</span>
          </div>
        </a>
        <a class="dropdown-item d-flex align-items-center" href="#">
          <div class="mr-1">
            <div class="icon-circle bg-success">
              <i class="fas fa-donate text-white"></i>
            </div>
          </div>
          <div>
            <div class="small text-gray-500">December 7, 2019</div>
            $290.29 has be
          </div>
        </a>
        <a class="dropdown-item d-flex align-items-center" href="#">
          <div class="mr-1">
            <div class="icon-circle bg-warning">
              <i class="fas fa-exclamation-triangle text-white"></i>
            </div>
          </div>
          <div>
            <div class="small text-gray-500">December 2, 2019</div>
            Spending Alert: We'v.
          </div>
        </a>
        <a class="dropdown-item text-center small text-gray-500" href="#">Show All Alerts</a>
      </div>
    </li>
    <!-- Nav Item - Messages -->
    <li class="nav-item dropdown no-arrow " data-toggle="tooltip" data-placement="bottom" title="Mensajes">
      <a class="nav-link dropdown-toggle" href="#" id="msgDropdown" role="button" data-toggle="dropdown"
        aria-haspopup="true" aria-expanded="false">
        <i class="far fa-envelope"></i>
        <span class="badge badge-warning badge-counter">7</span>
        <!-- Counter - Alerts -->
      </a>
      <!-- Dropdown - Alerts -->
      <div class="dropdown-list dropdown-menu dropdown-menu-right shadow-lg animated--grow-in"
        aria-labelledby="msgDropdown">
        <h6 class="dropdown-header">
          Mensajes
        </h6>
        <a class="dropdown-item d-flex align-items-center" href="#">

          <div>
            <div class="small text-gray-500">December 12, 2019</div>
            <span class="font-weight-bold">A new monthly re</span>
          </div>
        </a>
        <a class="dropdown-item d-flex align-items-center" href="#">

          <div>
            <div class="small text-gray-500">December 7, 2019</div>
            $290.29 has be
          </div>
        </a>
        <a class="dropdown-item d-flex align-items-center" href="#">

          <div>
            <div class="small text-gray-500">December 2, 2019</div>
            Spending Alert: We'v.
          </div>
        </a>
        <a class="dropdown-item text-center small text-gray-500" href="#">Show All Messages</a>
      </div>
    </li>
    <div class="topbar-divider d-none d-sm-block"></div>
    <!-- Nav Item - User Information -->
    <li class="nav-item dropdown no-arrow my-auto" data-toggle="tooltip" data-placement="bottom" title="Perfil">
      <?php if($this->user) : 
            $obj = new Application_Model_DbTable_Usuario();
            $usuario= $obj->listar_usuario($this->user->usu_id);
            $ultima_conexion = $obj->obtiene_ultima_conexion_usuario($this->user->usu_id);
      ?>
      <a class="nav-link dropdown-toggle " href="#"
        id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <i class="far fa-user"></i>
          <?php 
            else : ?>
          <a class=" btn btn-outline-primary btn-sm" href="<?php echo $this->baseUrl();?>/auth/login">
            <span class="font-weight-bold">Login</span>
          </a>
          <?php  endif; ?>
      </a>
      <!-- Dropdown - User Information -->
      <div class="dropdown-list dropdown-menu dropdown-menu-right shadow-lg animated--grow-in" aria-labelledby="userDropdown">

        <h6 class="dropdown-header">MI CUENTA</h6>
        <div class="dropdown-item d-flex justify-content-between mt-2">
          <a class=" btn btn-outline-<?php echo $this->escape($usuario->perf_color); ?>
             btn-circle btn-lg" href="<?php echo $this->baseUrl();?>/usuarios/perfil">
            <span class="text-uppercase font-weight-bold"><?php echo $usuario->usu_iniciales; ?></span>
          </a>
          <div >
            <i class="far fa-fw fa-user"></i>
            <strong><?php echo $this->escape($usuario->usu_nombres." ".$usuario->usu_apellidos); ?></strong>
            <br>
            <i class="far fa-fw fa-envelope"></i> <span class="text-gray-600 font-italic">
              <?php  echo $this->escape($usuario->correo); ?> </span>
            <br>
            <span class="text-primary"><?php  echo $this->escape($usuario->perf_nombre); ?> </span>


            </div>
        </div>
        <span class="d-flex justify-content-center text-xxs">
          <strong>
            Ultimo acceso:
            <?php  echo $this->escape($ultima_conexion->dias." dias ".$ultima_conexion->horas." horas ".$ultima_conexion->min." min"); ?></strong>
        </span>
        <!-- Divider -->
        <div class="btn-group d-flex justify-content-end" role="group" aria-label="Basic example">
          <button class=" btn btn-outline-dark btn-sm  border-0"
            onclick="cambiarClaveU('<?php echo $this->user->usu_id; ?>')">
            <i class="fas fa-key fa-sm fa-fw"></i> <span>Cambiar contraseña</span>
          </button>
        </div>
        <div class="btn-group d-flex justify-content-end" role="group" aria-label="Basic example">
          <button type="button" class=" btn btn-outline-primary btn-sm  border-0"
            onclick="window.location.href=`<?php echo $this->baseUrl();?>/usuarios/perfil`">
            <i class="fas fa-users-cog fa-sm fa-fw mr-2"></i>
            <span>Perfil</span>
          </button>
          <button type="button" class=" btn btn-outline-danger btn-sm  border-0" onclick="logout()">
            <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2"></i>
            <span>Salir</span>
          </button>
        </div>
      </div>
    </li>
  </ul>
</nav>
<!-- End of Topbar -->