<!-- Page Heading -->
<div class="d-flex justify-content-between mx-sm-1 my-sm-1">
   <h4 class="h4  text-gray-800 text-capitalize"><?php echo $this->controlador; ?>
   <i class="fas fa-fw <?php echo $this->icono; ?> text-gray-700"></i></h4>
   
   
   <ol class="breadcrumb bg-transparent text-xxs">
       <li class="breadcrumb-item"><a href="<?php echo $this->baseUrl(); ?>"><i class="fas fa-home"></i>
           Inicio</a></li>
           
       <li class="breadcrumb-item text-capitalize">
           <a href="<?php echo $this->baseUrl(); ?>/<?php echo $this->controlador; ?>">
            <i class="fas fa-fw <?php echo $this->icono; ?>"></i>
               <?php echo $this->controlador; ?></a></li>
       <li class="breadcrumb-item active text-capitalize" aria-current="page"><?php echo $this->accion; ?></li>
   </ol>
 </div>
 <!-- Page Heading -->