<!-- Bootstrap core JavaScript-->
<script src="<?php echo $this->baseUrl(); ?>/vendor/jquery/jquery.min.js"></script>
<!-- Core plugin JavaScript-->
<script src="<?php echo $this->baseUrl(); ?>/vendor/jquery-easing/jquery.easing.min.js"></script>
<script src="<?php echo $this->baseUrl(); ?>/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
<script src="<?php echo $this->baseUrl(); ?>/vendor/select2/js/select2.full.js"></script>
<script src="<?php echo $this->baseUrl(); ?>/vendor/sweetalert2/js/sweetalert2.min.js"></script>



<!-- Custom scripts for all pages-->
<script src="<?php echo $this->baseUrl(); ?>/assets/js/sb-admin-2.js"></script>
<!-- Page level plugins -->
<script src="<?php echo $this->baseUrl(); ?>/vendor/datatables/jquery.dataTables.min.js"></script>
<script src="<?php echo $this->baseUrl(); ?>/vendor/datatables/dataTables.bootstrap4.min.js"></script>
<!-- Page level custom scripts -->
<script src="<?php echo $this->baseUrl(); ?>/functions/auth.js"></script>
<script src="<?php echo $this->baseUrl(); ?>/functions/dataTables.js"></script>
<script src="<?php echo $this->baseUrl(); ?>/functions/usuarios.js"></script>

