<!-- Bootstrap core JavaScript-->
<script src="<?php echo $this->baseUrl(); ?>/vendor/jquery/jquery.min.js"></script>
<!-- Core plugin JavaScript-->
<script src="<?php echo $this->baseUrl(); ?>/vendor/jquery-easing/jquery.easing.min.js"></script>
<script src="<?php echo $this->baseUrl(); ?>/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
<script src="<?php echo $this->baseUrl(); ?>/vendor/sweetalert2/js/sweetalert2.min.js"></script>




<!-- Page level plugins -->
<script src="<?php echo $this->baseUrl(); ?>/vendor/datatables/jquery.dataTables.min.js"></script>
<script src="<?php echo $this->baseUrl(); ?>/vendor/datatables/dataTables.bootstrap4.min.js"></script>
<script src="<?php echo $this->baseUrl(); ?>/vendor/datatables/dataTables.fixedHeader.min.js"></script>
<script src="<?php echo $this->baseUrl(); ?>/vendor/datatables/dataTables.responsive.min.js"></script>
<script src="<?php echo $this->baseUrl(); ?>/vendor/datatables/responsive.bootstrap4.min.js"></script>
<script src="<?php echo $this->baseUrl(); ?>/vendor/datatables/dataTables.buttons.min.js"></script>
<script src="<?php echo $this->baseUrl(); ?>/vendor/datatables/buttons.bootstrap4.min.js"></script>
<script src="<?php echo $this->baseUrl(); ?>/vendor/datatables/buttons.flash.min.js"></script>
<script src="<?php echo $this->baseUrl(); ?>/vendor/datatables/jszip.min.js"></script>
<script src="<?php echo $this->baseUrl(); ?>/vendor/datatables/pdfmake.min.js"></script>
<script src="<?php echo $this->baseUrl(); ?>/vendor/datatables/vfs_fonts.js"></script>
<script src="<?php echo $this->baseUrl(); ?>/vendor/datatables/buttons.html5.min.js"></script>
<script src="<?php echo $this->baseUrl(); ?>/vendor/datatables/buttons.print.min.js"></script>

<script src="<?php echo $this->baseUrl(); ?>/vendor/select2/js/select2.full.js"></script>
<script src="<?php echo $this->baseUrl(); ?>/vendor/bootstrap4-toggle/js/bootstrap4-toggle.min.js"></script>

<script src="<?php echo $this->baseUrl(); ?>/vendor/moment.js/moment.min.js"></script>
<script src="<?php echo $this->baseUrl(); ?>/vendor/moment.js/es.js"></script>

<script src="<?php echo $this->baseUrl(); ?>/vendor/chart.js/Chart.min.js"></script>

<!-- Page level custom scripts -->
<script src="<?php echo $this->baseUrl(); ?>/functions/auth.js"></script>
<script src="<?php echo $this->baseUrl(); ?>/functions/dataTables.js"></script>
<script src="<?php echo $this->baseUrl(); ?>/functions/usuarios.js"></script>
<script src="<?php echo $this->baseUrl(); ?>/functions/dashboard.js"></script>

<!-- Custom scripts for all pages-->
<script src="<?php echo $this->baseUrl(); ?>/assets/js/sb-admin-2.js"></script>
