<!-- Bootstrap core JavaScript-->
<script src="<?php echo $this->baseUrl; ?>/vendor/jquery/jquery.min.js"></script>
<!-- Core plugin JavaScript-->
<script src="<?php echo $this->baseUrl; ?>/vendor/jquery-easing/jquery.easing.min.js"></script>
<script src="<?php echo $this->baseUrl; ?>/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
<script src="<?php echo $this->baseUrl; ?>/vendor/select2/js/select2.full.js"></script>
<script src="<?php echo $this->baseUrl; ?>/vendor/sweetalert2/js/sweetalert2.min.js"></script>



<!-- Custom scripts for all pages-->
<script src="<?php echo $this->baseUrl; ?>/assets/js/sb-admin-2.min.js"></script>
<!-- Page level plugins -->
<script src="<?php echo $this->baseUrl; ?>/vendor/datatables/jquery.dataTables.min.js"></script>
<script src="<?php echo $this->baseUrl; ?>/vendor/datatables/dataTables.bootstrap4.min.js"></script>
<!-- Page level custom scripts -->
<script src="<?php echo $this->baseUrl; ?>/functions/auth.js"></script>
<script src="<?php echo $this->baseUrl; ?>/functions/dataTables.js"></script>

<script >
   // Example starter JavaScript for disabling form submissions if there are invalid fields
   (function() {
       'use strict';
       window.addEventListener('load', function() {
           // Fetch all the forms we want to apply custom Bootstrap validation styles to
           var forms = document.getElementsByClassName('needs-validation');
           // Loop over them and prevent submission
           var validation = Array.prototype.filter.call(forms, function(form) {
               form.addEventListener('submit', function(event) {
                   if (form.checkValidity() === false) {
                       event.preventDefault();
                       event.stopPropagation();
                   }
                   form.classList.add('was-validated');
               }, false);
           });
       }, false);
   })();
</script>