<!-- Sidebar -->
<ul class="navbar-nav bg-gray-900 sidebar toggled sidebar-dark accordion shadow " id="accordionSidebar">
  <!-- Sidebar - Brand -->
  <a class="sidebar-brand d-flex align-items-center justify-content-center"
    href="<?php echo $this->baseUrl();?>/panel_de_control">
    <div class="sidebar-brand-icon">
      PG - CAM
    </div>
  </a>
  <!-- Divider -->
  <hr class="sidebar-divider my-0">
  <!-- Nav Item - Dashboard -->
  <li class="nav-item <?php echo $this->setActive('index','dashboard'); ?>">
    <a class="nav-link py-1" href="<?php echo $this->baseUrl();?>/panel_de_control">
      <i class="fas fa-fw fa-chart-pie "></i>
      <span>Dashboard</span></a>
  </li>
  <div>
<!-- Divider -->
<hr class="sidebar-divider">
<!-- Heading -->
<div class="sidebar-heading">
  Paciente
</div>
<li class="nav-item <?php echo $this->setActive('paciente','listar'); ?>">
  <a class="nav-link py-1" href="<?php echo $this->baseUrl();?>/listar_paciente">
    <i class="fas fa-fw fa-list "></i>
    <span>Listar</span></a>
</li>
<li class="nav-item <?php echo $this->setActive('paciente','registrar'); ?>">
  <a class="nav-link py-1" href="<?php echo $this->baseUrl();?>/registrar_paciente">
    <i class="fas fa-fw fa-file-signature"></i>
    <span>Registrar</span></a>
</li>
<li class="nav-item <?php echo $this->setActive('paciente','asignar'); ?>">
  <a class="nav-link py-1" href="<?php echo $this->baseUrl();?>/asignar_cama_paciente">
    <i class="fas fa-fw fa-procedures "></i>
    <span>Asignar cama</span></a>
</li>
<li class="nav-item <?php echo $this->setActive('paciente','cambio'); ?>">
  <a class="nav-link py-1" href="<?php echo $this->baseUrl();?>/cambio_cama_paciente">
    <i class="fas fa-fw fa-exchange-alt "></i>
    <span>Cambio / Egreso</span></a>
</li>
  </div>
  
  
  <!-------------------------IMPORTANTE PARA OCULTAR LOS ACCESOS -->
  <?php if(isset($this->user) /*&&($this->user->perf_id==1)*/) : ?>
  <div>
    <!-- Divider -->
    <hr class="sidebar-divider">
    <!-- Heading -->
    <div class="sidebar-heading">Gestion</div>
    <!-- Nav Item - Charts -->
    <li class="nav-item <?php echo $this->setActive('usuarios','index'); echo $this->setActive('usuarios','perfiles');?> ">
      <a class="nav-link collapsed py-1" data-toggle="collapse" data-target="#collapseUtilities2" aria-expanded="true"
        aria-controls="collapseUtilities" href="">
        <i class="fas fa-fw fa-users-cog"></i>
        <span>Usuarios</span></a>
      <div id="collapseUtilities2" class="collapse" aria-labelledby="headingUtilities" data-parent="#accordionSidebar">
        <div class="bg-light  collapse-inner rounded">
          <h6 class="collapse-header text-gray-800"><strong>Acciones:</strong></h6>
          <a class="collapse-item py-1" href="<?php echo $this->baseUrl();?>/listar_usuarios">
            <i class="fas fa-fw fa-users"></i> <span>Usuarios</span></a>

          <a class="collapse-item py-1" href="<?php echo $this->baseUrl();?>/listar_perfiles">
            <i class="fas fa-fw fa-user-tag"></i> <span>Perfiles</span></a>

        </div>
      </div>
    </li>
    <!-- Nav Item - Charts -->
    <li class="nav-item <?php echo $this->setActive('areas','index'); ?>">
      <a class="nav-link py-1" href="<?php echo $this->baseUrl();?>/areas">
        <i class="fas fa-fw fa-table"></i>
        <span>Areas</span></a>
    </li>
    <!-- Nav Item - Tables -->
    <li class="nav-item <?php echo $this->setActive('pisos','index'); ?>">
      <a class="nav-link py-1" href="<?php echo $this->baseUrl();?>/pisos">
        <i class="fas fa-fw fa-layer-group"></i>
        <span>Pisos</span></a>
    </li>
    <li class="nav-item <?php echo $this->setActive('especialidades','index'); ?>">
      <a class="nav-link py-1" href="<?php echo $this->baseUrl();?>/especialidades">
        <i class="fas fa-fw fa-medkit"></i>
        <span>Especialidades</span></a>
    </li>
    <!-- Nav Item - Tables -->
    <li class="nav-item <?php echo $this->setActive('habitaciones','index'); ?>">
      <a class="nav-link py-1" href="<?php echo $this->baseUrl();?>/habitaciones">
        <i class="fas fa-fw fa-door-open"></i>
        <span>Habitaciones</span></a>
    </li>
    <!-- Nav Item - Tables -->
    <li class="nav-item <?php echo $this->setActive('camas','index'); ?>">
      <a class="nav-link py-1" href="<?php echo $this->baseUrl();?>/camas">
        <i class="fas fa-fw fa-bed"></i>
        <span>Camas</span></a>
    </li>
    <li
      class="nav-item <?php echo $this->setActive('cie10','descripcion'); echo $this->setActive('cie10','categoria'); echo $this->setActive('cie10','capitulo');?>">
      <a class="nav-link collapsed py-1" data-toggle="collapse" data-target="#collapseUtilities3" aria-expanded="true"
        aria-controls="collapseUtilities" href="#">
        <i class="fas fa-fw fa-heartbeat"></i>
        <span>CIE-10</span></a>
      <div id="collapseUtilities3" class="collapse" aria-labelledby="headingUtilities" data-parent="#accordionSidebar">
        <div class="bg-light  collapse-inner rounded">
          <h6 class="collapse-header text-gray-800"><strong>Buscar:</strong></h6>
          <a class="collapse-item py-1" href="<?php echo $this->baseUrl();?>/cie10/descripcion">
            <i class="fas fa-fw fa-chevron-right"></i> <span>Por descripcion</span></a>
          <a class="collapse-item py-1" href="<?php echo $this->baseUrl();?>/cie10/categoria">
            <i class="fas fa-fw fa-chevron-right"></i> <span>Por categoria</span></a>
          <a class="collapse-item py-1" href="<?php echo $this->baseUrl();?>/cie10/capitulo">
            <i class="fas fa-fw fa-chevron-right"></i> <span>Por capitulo</span></a>
    
        </div>
      </div>
    </li>
  </div>
  <?php  endif ?> 


  <!-- Divider -->
  <hr class="sidebar-divider">
  <!-- Heading -->
  <div class="sidebar-heading">Reportes</div>
  <!-- Nav Item - Charts -->
  <li class="nav-item <?php echo $this->setActive('reportes','index'); ?>">
    <a class="nav-link py-1" href="<?php echo $this->baseUrl();?>/reportes">
      <i class="fas fa-fw fa-chart-line"></i>
      <span>Reportes</span></a>
  </li>

  <!-- Divider -->
  <hr class="sidebar-divider">
  <!-- Heading -->
  <div class="sidebar-heading">config</div>
  
  <!-- Nav Item - Charts -->
  <li class="nav-item <?php echo $this->setActive('database','index'); ?>">
    <a class="nav-link py-1" href="<?php echo $this->baseUrl();?>/database">
      <i class="fas fa-fw fa-server"></i>
      <span>Base de datos</span></a>
  </li>
  <!-- Divider -->
  <hr class="sidebar-divider d-none d-md-block">
  <!-- Sidebar Toggler (Sidebar) -->
  <div class="text-center d-none d-md-inline">
    <button class="rounded-circle border-0" id="sidebarToggle"></button>
  </div>
</ul>
<!-- End of Sidebar -->