<?php echo $this->doctype() ?>

<html >

<head>
  <?php echo $this->render('_head.phtml'); ?>
  <?php echo $this->render('_scripts.phtml'); ?>
</head>

<body id="page-top" class="sidebar-toggled ">
  
  <!-- Page Wrapper -->
  <div id="wrapper" >
    <!-- Sidebar -->
    <?php echo $this->render('_sidebar.phtml'); ?>
    <!-- End of Sidebar -->
    <!-- Content Wrapper -->
    <div id="content-wrapper" class="bg-gray-200 d-flex flex-column">
      <!-- Main Content -->
      <div id="content">
        <!-- Topbar -->
        <?php echo $this->render('_navbar.phtml'); ?>
        <!-- End of Topbar -->
        <!-- Begin Page Content -->
        <div class="container-fluid pt-4">
          <!-- Page Heading -->
          <!-- Page Heading -->
          <?php echo $this->layout()->content; ?>
        </div>
        <!-- /.container-fluid -->
      </div>
      <!-- End of Main Content -->
      <div class="bg bg-white shadow">
        <?php echo $this->render('_footer.phtml'); ?>
      </div>
      
    </div>
    <!-- End of Content Wrapper -->
  </div>
  <!-- End of Page Wrapper -->
  <!-- Scroll to Top Button-->
  <a class="scroll-to-top rounded " href="#page-top">
    <i class="fas fa-angle-up "></i>
  </a>
  <?php echo $this->render('_modalPassword.phtml'); ?>

  <input type="hidden" name="dir" id="dir" readonly="readonly" value="<?php echo $this->baseUrl(); ?>">
  
  
</body>

</html>