<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">
  
  <title><?php echo $this->titulo;?></title>
  <!-- Custom fonts for this template-->
  <link href="<?php echo $this->baseUrl; ?>/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
  <link href="<?php echo $this->baseUrl; ?>/vendor/sweetalert2/css/sweetalert2.min.css" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
  <!-- Custom styles for this template-->
  <link href="<?php echo $this->baseUrl; ?>/assets/css/sb-admin-2.css" rel="stylesheet">
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link rel="icon" type="image/vnd.microsoft.icon" href="<?php echo $this->baseUrl; ?>/favico.ico">
  <script src="<?php echo $this->baseUrl; ?>/vendor/sweetalert2/js/sweetalert2.min.js"></script>
 
</head>
<body id="page-top">
  <!-- Page Wrapper -->
  <div id="wrapper">
    <!-- Sidebar -->
    <ul class="navbar-nav bg bg-gray-900 sidebar sidebar-dark accordion shadow" id="accordionSidebar" >
      <!-- Sidebar - Brand -->
      <a class="sidebar-brand d-flex align-items-center justify-content-center" href="<?php echo $this->url(array('controller' => 'index', 'action' => 'index')); ?>">
        <div class="sidebar-brand-icon ">
          <link rel="icon" type="image/vnd.microsoft.icon" href="<?php echo $this->baseUrl; ?>/favico.ico">
          <img src="<?php echo $this->baseUrl; ?>/favico.ico"></img>
        </div>
        <div class="sidebar-brand-text mx-3">PG - CAM <sup></sup></div>
      </a>
      <!-- Divider -->
      <hr class="sidebar-divider my-0">
      <!-- Nav Item - Dashboard -->
      <li class="nav-item active">
        <a class="nav-link" href="<?php echo $this->url(array('controller' => 'index', 'action' => 'index')); ?>">
          <i class="fas fa-fw fa-tachometer-alt "></i>
          <span>Dashboard</span></a>
      </li>
      <!-- Divider -->
      <hr class="sidebar-divider">
      <!-- Heading -->
      <div class="sidebar-heading">
        Proceso
      </div>
      <!-- Nav Item - Utilities Collapse Menu -->
      <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseUtilities" aria-expanded="true" aria-controls="collapseUtilities">
          <i class="fas fa-fw fa-procedures"></i>
          <span>Paciente</span>
        </a>
        <div id="collapseUtilities" class="collapse" aria-labelledby="headingUtilities" data-parent="#accordionSidebar">
          <div class="bg-gray-300  collapse-inner rounded">
            <h6 class="collapse-header"><strong>Acciones:</strong></h6>
            <a class="collapse-item" href=""><i class="fas fa-fw fa-list"></i> Listar</a>
            <a class="collapse-item" href=""><i class="fas fa-fw fa-sign-in-alt"></i> Ingreso</a>
            <a class="collapse-item" href=""><i class="fas fa-fw fa-exchange-alt"></i> Cambio / Egreso</a>
          </div>
        </div>
      </li>
      <!-- Divider -->
      <hr class="sidebar-divider">
      <!-- Heading -->
      <div class="sidebar-heading">Gestion</div>
      <!-- Nav Item - Charts -->
      <li class="nav-item">
        <a class="nav-link" href="<?php echo $this->url(array('controller' => 'areas', 'action' => 'index')); ?>">
          <i class="fas fa-fw fa-table"></i>
          <span>Areas</span></a>
      </li>
      <!-- Nav Item - Tables -->
      <li class="nav-item">
        <a class="nav-link" href="<?php echo $this->url(array('controller' => 'pisos', 'action' => 'index')); ?>">
          <i class="fas fa-fw fa-layer-group"></i>
          <span>Pisos</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="<?php echo $this->url(array('controller' => 'especialidades', 'action' => 'index')); ?>">
          <i class="fas fa-fw fa-medkit"></i>
          <span>Especialidades</span></a>
      </li>
      <!-- Nav Item - Tables -->
      <li class="nav-item">
        <a class="nav-link" href="<?php echo $this->url(array('controller' => 'habitaciones', 'action' => 'index')); ?>">
          <i class="fas fa-fw fa-h-square"></i>
          <span>Habitaciones</span></a>
      </li>
      <!-- Nav Item - Tables -->
      <li class="nav-item">
        <a class="nav-link" href="<?php echo $this->url(array('controller' => 'camas', 'action' => 'index')); ?>">
          <i class="fas fa-fw fa-bed"></i>
          <span>Camas</span><span class="badge badge-danger badge-counter">7</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="<?php echo $this->url(array('controller' => 'cie10', 'action' => 'index')); ?>">
          <i class="fas fa-fw fa-heartbeat"></i>
          <span>CIE-10</span></a>
      </li>
      <!-- Divider -->
      <hr class="sidebar-divider d-none d-md-block">
      <!-- Sidebar Toggler (Sidebar) -->
      <div class="text-center d-none d-md-inline">
        <button class="rounded-circle border-0" id="sidebarToggle"></button>
      </div>
    </ul>
    <!-- End of Sidebar -->
    <!-- Content Wrapper -->
    <div id="content-wrapper" class="d-flex flex-column">
      <!-- Main Content -->
      <div id="content">
        <!-- Topbar -->
        <nav class="navbar  navbar-expand bg bg-transparent navbar-light topbar mb-1 static-top shadow " >
          <!-- Sidebar Toggle (Topbar) -->
            
         
          <button id="sidebarToggleTop" class="btn btn-link btn-block rounded-circle border-0 ">
            <i class="fas fa-bars " aria-hidden="true"></i>
          </button>
          
          <!-- Topbar Search -->
          <form class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search">
            <div class="input-group">
              <input type="text" class="form-control bg-light border-1 small" placeholder="Buscar..." aria-label="Search" aria-describedby="basic-addon2">
              <div class="input-group-append">
                <button class="btn btn-primary" type="button">
                  <i class="fas fa-search fa-sm text-white"></i>
                </button>
              </div>
            </div>
          </form>
          <!-- <img class="img-fluid" src="<?php echo $this->baseUrl; ?>/assets/img/logo_msp_2019.png" 
            width="200" height="100" alt=""> -->
          <!-- Topbar Navbar -->
          <ul class="navbar-nav ml-auto">
            <!-- Nav Item - Search Dropdown (Visible Only XS) -->
            <li class="nav-item dropdown no-arrow d-sm-none">
              <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-search fa-fw text-primary"></i>
              </a>
              <!-- Dropdown - Messages -->
              <div class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in" aria-labelledby="searchDropdown">
                <form class="form-inline mr-auto w-100 navbar-search">
                  <div class="input-group">
                    <input type="text" class="form-control bg-light border-1 small" placeholder="Buscar..." aria-label="Search" aria-describedby="basic-addon2">
                    <div class="input-group-append">
                      <button class="btn btn-primary" type="button">
                        <i class="fas fa-search fa-sm text-white"></i>
                      </button>
                    </div>
                  </div>
                </form>
              </div>
                
             
            </li>
            <!-- Nav Item - Alerts -->
            <li class="nav-item dropdown no-arrow mx-1">
              <a class="nav-link dropdown-toggle" href="#" id="alertsDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-bell fa-fw text-primary"></i>
                <!-- Counter - Alerts -->
                <span class="badge badge-danger badge-counter">3+</span>
              </a>
              <!-- Dropdown - Alerts -->
              <div class="dropdown-list dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="alertsDropdown">
                <h6 class="dropdown-header">
                  Alerts Center
                </h6>
                <a class="dropdown-item d-flex align-items-center" href="#">
                  <div class="mr-3">
                    <div class="icon-circle bg-primary">
                      <i class="fas fa-file-alt text-white"></i>
                    </div>
                  </div>
                  <div>
                    <div class="small text-gray-500">December 12, 2019</div>
                    <span class="font-weight-bold">A new monthly report is ready to download!</span>
                  </div>
                </a>
                <a class="dropdown-item d-flex align-items-center" href="#">
                  <div class="mr-3">
                    <div class="icon-circle bg-success">
                      <i class="fas fa-donate text-white"></i>
                    </div>
                  </div>
                  <div>
                    <div class="small text-gray-500">December 7, 2019</div>
                    $290.29 has been deposited into your account!
                  </div>
                </a>
                <a class="dropdown-item d-flex align-items-center" href="#">
                  <div class="mr-3">
                    <div class="icon-circle bg-warning">
                      <i class="fas fa-exclamation-triangle text-white"></i>
                    </div>
                  </div>
                  <div>
                    <div class="small text-gray-500">December 2, 2019</div>
                    Spending Alert: We've noticed unusually high spending for your account.
                  </div>
                </a>
                <a class="dropdown-item text-center small text-gray-500" href="#">Show All Alerts</a>
              </div>
            </li>
            <!-- Nav Item - Messages -->
            
            <div class="topbar-divider d-none d-sm-block"></div>
            <!-- Nav Item - User Information -->
            <li class="nav-item dropdown no-arrow">
              <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-user fa-fw text-primary"></i>
                
                <span class="px-2 py-2 d-none d-lg-inline text-primary ">
                    <?php if($this->user) :
                        echo $this->escape($this->user->usu_nombres);
                        endif; ?>
                </span>
              </a>
              <!-- Dropdown - User Information -->
              <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">
                <a class="dropdown-item" href="#">
                  <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                  Perfil
                </a>
                <a class="dropdown-item" href="#">
                  <i class="fas fa-cogs fa-sm fa-fw mr-2 text-gray-400"></i>
                  Configuracion
                </a>
                <div class="dropdown-divider"></div>
                <button class="dropdown-item" onclick="logout()" >
                  <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                  Salir
                </button>
              </div>
            </li>
          </ul>
        </nav>
        <!-- End of Topbar -->
        <!-- Begin Page Content -->
        <div class="container-fluid py-1">
          <!-- Page Heading -->
          <?php echo $this->layout()->content; ?> 
        </div>
        <!-- /.container-fluid -->
      </div>
      <!-- End of Main Content -->
      <!-- Footer -->
      <footer class="sticky-footer ">
        <div class="container my-auto d-flex justify-content-between">
          <div class="copyright text-center my-auto">
            <span><strong><a href="https://www.ups.edu.ec/" target="_blank">
            Universidad Politecnica Salesiana</a> &copy; <?php echo date("Y");?>
          </strong></span>
          </div>
          
          <div class="copyright text-center my-auto">
            <span>Version <strong>1.0.0</strong></span>
          </div>
          <!-- <img src="http://framework.zend.com/images/PoweredBy_ZF_4LightBG.png" /> -->
        </div>
      </footer>
      <!-- End of Footer -->
    </div>
    <!-- End of Content Wrapper -->
  </div>
  <!-- End of Page Wrapper -->
  <!-- Scroll to Top Button-->
  <a class="scroll-to-top rounded" href="#page-top">
    <i class="fas fa-angle-up"></i>
  </a>
  <!-- Bootstrap core JavaScript-->
  <script src="<?php echo $this->baseUrl; ?>/vendor/jquery/jquery.min.js"></script>
  <script src="<?php echo $this->baseUrl; ?>/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

  <!-- Core plugin JavaScript-->
  <script src="<?php echo $this->baseUrl; ?>/vendor/jquery-easing/jquery.easing.min.js"></script>

  <!-- Custom scripts for all pages-->
  <script src="<?php echo $this->baseUrl; ?>/assets/js/sb-admin-2.min.js"></script>
  <!-- Page level plugins -->
  <script src="<?php echo $this->baseUrl; ?>/vendor/datatables/jquery.dataTables.min.js"></script>
  <script src="<?php echo $this->baseUrl; ?>/vendor/datatables/dataTables.bootstrap4.min.js"></script>
  <!-- Page level custom scripts -->
  <script src="<?php echo $this->baseUrl; ?>/assets/js/demo/datatables-demo.js"></script>
  <script src="<?php echo $this->baseUrl; ?>/functions/auth.js"></script>
  <script src="<?php echo $this->baseUrl; ?>/functions/dataTables.js"></script>

  <input type="hidden" name="dir" id="dir" readonly="readonly"  value="<?php echo $this->baseUrl; ?>">
  <script >
      // Example starter JavaScript for disabling form submissions if there are invalid fields
      (function() {
          'use strict';
          window.addEventListener('load', function() {
              // Fetch all the forms we want to apply custom Bootstrap validation styles to
              var forms = document.getElementsByClassName('needs-validation');
              // Loop over them and prevent submission
              var validation = Array.prototype.filter.call(forms, function(form) {
                  form.addEventListener('submit', function(event) {
                      if (form.checkValidity() === false) {
                          event.preventDefault();
                          event.stopPropagation();
                      }
                      form.classList.add('was-validated');
                  }, false);
              });
          }, false);
      })();

  </script>
</body>
</html>
