<!DOCTYPE html>
<html lang="en">

<head>
  <?php echo $this->render('_head.phtml'); ?>
</head>

<body  class="bg bg-gradient-light ">
  <div class="container">
    <div class="d-none d-lg-block py-5"></div>
    <div class="row  justify-content-center ">
      <div class="col-xl-8 col-lg-12 col-md-8 ">
        <div class="card bg-light border-0 rounded shadow-lg my-3 animated bounceInDown ">
          <div class="card-header justify-content-center ">
            <h6 class="font-weight-bold  text-primary text-center pt-2">
              HOSPITAL GINECO OBSTÉTRICO PEDIÁTRICO DE NUEVA AURORA LUZ ELENA ARISMENDI</h6>
          </div>
          <?php echo $this->layout()->content; ?>
          <div class="card-footer  px-0   py-2">
            <?php echo $this->render('_footer.phtml'); ?>
          </div>
        </div>
      </div>
    </div>
  </div>
  <input type="hidden" name="dir" id="dir" readonly="readonly" value="<?php echo $this->baseUrl(); ?>">
  <!-- Modal -->
  <div class="modal fade " id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
    aria-hidden="true">
    <div class="modal-dialog modal-sm " role="document">
      <div class="modal-content ">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Recuperar contraseña</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <div class="row">
            <div class="col d-flex justify-content-center">
              <img class="img-fluid" height="100" width="100" src="<?php echo $this->baseUrl(); ?>/assets/img/forgot.svg"
                alt="Forgot">
            </div>
          </div>
          <div class="row">
            <div class="col">
              <div class="form-group">
                <input type="email" autofocus class="form-control form-control-user" id="recuperar" name="recuperar"
                  aria-describedby="correoHelp" required placeholder="Ingrese su correo electronico..." autocomplete="off"
                  onkeypress="validarCorreo()">
                <small id="correoHelp"></small>
              </div>
              <div id="mensaje">
              </div>
              <p class="small text-justify text-gray-500 ">A continuacion se enviará una clave provisional al correo
                ingresado.</p>
            </div>
          </div>
  
        </div>
        <div class="modal-footer justify-content-center">
          <button type="button" class="btn btn-primary btn-icon-split" onclick="recuperarclave()">
            <span class="icon text-white-50"><i class="fas fa-key"></i></span><span class="text">Recuperar
              contraseña</span></button>
        </div>
      </div>
    </div>
  </div>
  <?php echo $this->render('_scripts.phtml'); ?>

  

</body>

</html>