<?php echo $this->doctype() ?>

<html>

<head>
   <?php echo $this->render('_head.phtml'); ?>
   
</head>

<body id="page-top" class="bg bg-white " onload="mueveReloj();dt();">

   <!-- Page Wrapper -->
   <div id="wrapper">
      <div id="accordionSidebar" class=" accordion"></div>
      <!-- Content Wrapper -->
      <div id="content-wrapper" class="bg-transparent d-flex flex-column">
         <!-- Main Content -->
         <div id="content">
            <!-- Begin Page Content -->
            <div class="container-fluid  ">
               <!-- Page Heading -->
               <!-- Page Heading -->
               <?php echo $this->layout()->content; ?>
            </div>
            <!-- /.container-fluid -->
         </div>
         
      </div>
      <!-- End of Content Wrapper -->
   </div>
   <!-- End of Page Wrapper -->
   <!-- Scroll to Top Button-->
   <a class="scroll-to-top rounded " href="#page-top">
      <i class="fas fa-angle-up "></i>
   </a>

   <input type="hidden" name="dir" id="dir" readonly="readonly" value="<?php echo $this->baseUrl(); ?>">
   <?php echo $this->render('_scripts.phtml'); ?>

</body>

</html>