<div class="card ">
	<div class="card-header d-flex justify-content-between">
		<h5 class="m-0 font-weight-bold text-primary"><?php echo $this->titulo; ?></h5>
		<div>
			<div class="input-group input-group-sm ">
				<div class="input-group-prepend">
					<select name="opcionBusqueda" id="opcionBusqueda"
						class="btn btn-block dropdown-toggle border-primary text-primary " type="button"
						data-toggle="dropdown" aria-expanded="false" required autocomplete="off">
						<option value="">OPCION</option>
						<option value="1">EMERGENCIA</option>
						<option value="2">C EXTERNA</option>
					</select>

				</div>
				<input type="text" class="form-control border-primary" id="paciente_id" name="paciente_id"
					placeholder="Buscar por hc o cedula..." aria-label="Search" aria-describedby="buscar_paciente_hc"
					required autocomplete="off"
					onkeyup="if (event.keyCode == 13) DatosPaciente();">
				<div class="input-group-append">

					<button class="btn btn-primary" type="submit" onclick="DatosPaciente();">
						<i class="fas fa-search fa-sm"></i>
					</button>
				</div>

			</div>
		</div>

	</div>
	<div class="card-body">
		<div class="row ">
			<div class="col-sm-12">
				<div class="card border-left-primary shadow   text-xxs">
					<div class="card-header py-1">
						<?php echo $this->getEspecialidades(); ?>
					</div>
					<div class="card-body ">

						<div id="data_Table1" class="table-responsive text-center">
							<span class="text-danger">Seleccione un tipo de servicio <i class="fa fa-level-up-alt"></i></span>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="row ">
			<div class="col-sm-6 py-3 ">
				<div class="card border-left-primary shadow  text-xxs ">
					<div class="card-header d-flex justify-content-start">
						<h6 class="m-0 ">Diagnostico de ingreso</h6>
					</div>
					<div class="card-body ">
						<div class="row">
							<div class="col">
								<div id="" class="table-responsive">
									<?php echo $this->getDiagnosticos();?>
								</div>
								<button class="btn btn-primary btn-sm">Agregar diagnosticos</button>
							</div>
						</div>
					</div>
				</div>
			</div>
			<div class="col-sm-6 py-3 ">
				<div class="card border-left-primary shadow  text-xxs ">
					<div class="card-header d-flex justify-content-start">
						<h6 class="m-0 ">Detalle de asignacion de cama</h6>
					</div>
					<div class="card-body ">
						<div class="row">
							<div class="col-sm-7 table-responsive">

								<table class="table table-borderless table-sm  " id="tablaDatosPaciente">
									<tbody>
										<tr>
											<td>N Archivo: </td>
											<td><span class="text-uppercase" id="paciente_hc"></span></td>
										</tr>
										<tr>
											<td>Paciente:</td>
											<td><span class="text-uppercase" id="apellido_paterno"></span></td>
										</tr>
										<tr>
											<td>N Cedula:</td>
											<td><span class="text-uppercase" id="cedula"></span></td>
										</tr>
										<!-- <tr>
										<td>Fecha de nacimiento:</td>
										<td><span class="text-uppercase" id="fecha_n"></span></td>
										</tr>
		
										<td>Edad:</td>
										<td><span class="text-uppercase" id="Edad"></span></td>
										</tr>
										<tr>
											<td>Genero:</td>
											<td><span class="text-uppercase" id="Genero"></span></td>
										</tr> -->
									</tbody>
								</table>
							</div>
							<div class="col-sm-5 table-responsive">
								<input type="hidden" id="cama_id">
								<table class="table table-borderless table-sm  " id="tablaDatosPaciente2">
									<tbody>
										<tr>
											<td>Servicio</td>
											<td><span class="text-uppercase" id="servicio"></span></td>
										</tr>
										<tr>
											<td>Habitacion:</td>
											<td><span class="text-uppercase" id="habitacion"></span></td>
										</tr>
										<tr>
											<td>Cama:</td>
											<td><span class="text-uppercase" id="cama"></span></td>
										</tr>

									</tbody>
								</table>
							</div>

						</div>
						<div class="row">
							<div class="col-sm-12">
								<div id="" class="table-responsive ">
									<table class="table table-sm table-bordered ">
										<thead>
											<tr>
												<th></th>
												<th>DIAGNOSTICO</th>
												<th>CIE</th>
												<th>PRE</th>
												<th>DEF</th>
											</tr>

										</thead>
										<tbody>
											<tr>
												<th>1</th>
												<td></td>
												<td>

												</td>
												<td>
												</td>
												<td>
												</td>
											</tr>
											<tr>
												<th>2</th>
												<td>
												</td>
												<td></td>
												<td>
												</td>
												<td>
												</td>
											</tr>
											<tr>
												<th>3</th>
												<td>
												</td>
												<td></td>
												<td>
												</td>
												<td>
												</td>
											</tr>

										</tbody>
									</table>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="card-footer d-flex justify-content-between">
		<button class="btn btn-danger" type="button">Cancelar</button>
		<button class="btn btn-success" type="button">Finalizar</button>
	</div>
</div>