<div class="card  shadow ">
	<div class="card-header d-flex justify-content-between">
		 <h5 class="m-0 font-weight-bold text-primary"><?php echo $this->titulo; ?></h5>
		 <div>
			<form class="d-none d-sm-inline-block form-inline mr-auto ml-md-3  my-md-0 mw-100 navbar-search">
				<div class="input-group input-group-sm ">
					<div class="input-group-prepend">
						
						<select name="" id="" class="btn btn-block dropdown-toggle border-primary text-primary " 
						type="button" data-toggle="dropdown" aria-expanded="false">
							<option value="">OPCION</option>
							<option value="">EMERGENCIA</option>
							<option value="">C EXTERNA</option>
						</select>
					</div>
					<input type="text" class="form-control" placeholder="Buscar por hc o cedula..." 
				aria-label="Search" aria-describedby="buscar_paciente_hc">
				<div class="input-group-append">

					<button class="btn btn-primary" type="button">
						<i class="fas fa-search fa-sm"></i>
					</button>
				</div>
				</div>
			</form>	
	</div>
	</div>
	<div class="card-body">
		
	</div>
</div>