<div class="card border-left-primary">
	<div class="card-header bg-light d-flex justify-content-between align-middle pb-0">
		<h4 class="h4  text-dark"><?php echo $this->titulo; ?>
			<i class="fas fa-fw <?php echo $this->icono; ?> text-dark"></i></h4>
		<nav aria-label="breadcrumb">
			<ol class="breadcrumb bg-transparent  text-xxs p-0 ">
				<li class="breadcrumb-item"><a href="<?php echo $this->baseUrl(); ?>/panel_de_control">
						<i class="fas fa-home "></i>Inicio</a></li>
				<li class="breadcrumb-item text-capitalize">
					<a href="<?php echo $this->baseUrl(); ?>/<?php echo $this->controlador; ?>">
						<i class="fas fa-fw fa-user-injured"></i>
						<?php echo $this->controlador; ?></a></li>
				<li class="breadcrumb-item active text-capitalize" aria-current="page">
					<?php echo $this->accion; ?></li>
			</ol>
		</nav>

	</div>

	<div class="card-body">
		<!-- Timelime example  -->
		<div class="row">
			<div class="col-md-12">
				<!-- The time line -->
				<div class="timeline text-white">
					<!-- timeline time label -->
					<div class="time-label">
						<span class="bg-danger">10 Feb. 2014</span>
					</div>
					<!-- /.timeline-label -->
					<!-- timeline item -->
					<div>
						<i class="fas fa-envelope bg-primary"></i>
						<div class="timeline-item">
							<span class="time"><i class="fas fa-clock"></i> 12:05</span>
							<h3 class="timeline-header"><a href="#">Support Team</a> sent you an email</h3>
		
							<div class="timeline-body">
								Etsy doostang zoodles disqus groupon greplin oooj voxy zoodles,
								weebly ning heekya handango imeem plugg dopplr jibjab, movity
								jajah plickers sifteo edmodo ifttt zimbra. Babblely odeo kaboodle
								quora plaxo ideeli hulu weebly balihoo...
							</div>
							<div class="timeline-footer">
								<a class="btn btn-primary btn-sm">Read more</a>
								<a class="btn btn-danger btn-sm">Delete</a>
							</div>
						</div>
					</div>
					<!-- END timeline item -->
					<!-- timeline item -->
					<div>
						<i class="fas fa-user bg-success"></i>
						<div class="timeline-item">
							<span class="time"><i class="fas fa-clock"></i> 5 mins ago</span>
							<h3 class="timeline-header no-border"><a href="#">Sarah Young</a> accepted your friend request</h3>
						</div>
					</div>
					<!-- END timeline item -->
					<!-- timeline item -->
					<div>
						<i class="fas fa-comments bg-warning"></i>
						<div class="timeline-item">
							<span class="time"><i class="fas fa-clock"></i> 27 mins ago</span>
							<h3 class="timeline-header"><a href="#">Jay White</a> commented on your post</h3>
							<div class="timeline-body">
								Take me to your leader!
								Switzerland is small and neutral!
								We are more like Germany, ambitious and misunderstood!
							</div>
							<div class="timeline-footer">
								<a class="btn btn-warning btn-sm">View comment</a>
							</div>
						</div>
					</div>
					<!-- END timeline item -->
					<!-- timeline time label -->
					<div class="time-label">
						<span class="bg-success">3 Jan. 2014</span>
					</div>
					<!-- /.timeline-label -->
					<!-- timeline item -->
					<div>
						<i class="fa fa-camera bg-purple"></i>
						<div class="timeline-item">
							<span class="time"><i class="fas fa-clock"></i> 2 days ago</span>
							<h3 class="timeline-header"><a href="#">Mina Lee</a> uploaded new photos</h3>
							<div class="timeline-body">
								<img src="http://placehold.it/150x100" alt="...">
								<img src="http://placehold.it/150x100" alt="...">
								<img src="http://placehold.it/150x100" alt="...">
								<img src="http://placehold.it/150x100" alt="...">
								<img src="http://placehold.it/150x100" alt="...">
							</div>
						</div>
					</div>
					<!-- END timeline item -->
					<div>
						<i class="fas fa-clock bg-secondary"></i>
					</div>
				</div>
			</div>
			<!-- /.col -->
		</div>
		<!-- /.timeline -->
	</div>
</div>