<div class="card border-left-primary mb-4">
	<div class="card-header bg-light d-flex justify-content-between align-middle pb-0">
		<h4 class="h4  text-dark"><?php echo $this->titulo; ?>
			<i class="fas fa-fw fa-table text-dark"></i></h4>
		<nav aria-label="breadcrumb">
			<ol class="breadcrumb bg-transparent  text-xxs p-0 ">
				<li class="breadcrumb-item"><a href="<?php echo $this->baseUrl(); ?>/panel_de_control">
						<i class="fas fa-home "></i>Inicio</a></li>
				<li class="breadcrumb-item text-capitalize">
					<a href="<?php echo $this->baseUrl(); ?>/<?php echo $this->controlador; ?>">
						<i class="fas fa-fw fa-user-injured"></i>
						<?php echo $this->controlador; ?></a></li>
				<li class="breadcrumb-item active text-capitalize" aria-current="page">
					<?php echo $this->accion; ?></li>
			</ol>
		</nav>

	</div>

	<div class="card-body">
		<div class="row ">
			<div class="col-md-12">

				<div id="data_Table" class="table-responsive text-xs">
					<?php echo $this->tabla_historial; ?>
				</div>
			</div>
		</div>
		<!-- Timelime example  -->

	</div>
</div>
<div class="card border-left-primary mb-4 ">
	<div class="card-header bg-light align-middle pb-0">
		<h4 class="h4  text-dark">Linea de tiempo
			<i class="fas fa-fw <?php echo $this->icono; ?> text-dark"></i></h4>
	</div>
	<div class="card-body ">
		<div class="row ">
			<div class="col-md-12 ">
				<!-- The time line -->
				<?php echo $this->time_line_paciente; ?>
			</div>
			<!-- /.col -->
		</div>
	</div>
	
</div>