<div class="card border-left-primary">
	<div class="card-header bg-light d-flex justify-content-between align-middle pb-0">
		<h4 class="h4  text-dark"><?php echo $this->titulo; ?>
			 <i class="fas fa-fw <?php echo $this->icono; ?> text-dark"></i></h4>
			 <nav aria-label="breadcrumb">
				  <ol class="breadcrumb bg-transparent  text-xxs p-0 ">
						<li class="breadcrumb-item"><a href="<?php echo $this->baseUrl(); ?>/panel_de_control">
							 <i class="fas fa-home "></i>Inicio</a></li>
						<li class="breadcrumb-item text-capitalize">
							 <a href="<?php echo $this->baseUrl(); ?>/<?php echo $this->controlador; ?>">
								  <i class="fas fa-fw fa-user-injured"></i>
								  <?php echo $this->controlador; ?></a></li>
						<li class="breadcrumb-item active text-capitalize" aria-current="page">
							 <?php echo $this->accion; ?></li>
				  </ol>
			 </nav>      
		
  </div>
	
	<div class="card-body">
		<input type="hidden" name="campoBusqueda" id="campoBusqueda" value="<?php if (isset($_GET['ci'])) echo $_GET['ci']; ?>">
		<div class="d-flex justify-content-between pb-2">
			<div class="text-center align-content-center" id="exportButtons"></div>
			<a type="button" class="btn btn-success btn-icon-split btn-sm" href="<?php echo $this->baseUrl();?>/registrar_paciente">
				<span class="icon text-white-50"><i class="fas fa-plus"></i></span><span class="text">Agregar</span>
		  </a>
			 
			
	  </div>
		<div id="data_Table" class="table-responsive text-xs">
			<?php echo $this->data; ?>
		</div>
	</div>
</div>
<!-- formulario Modal-->
<!-- <div class="modal fade" id="formModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
	aria-hidden="true">
	<div class="modal-dialog " role="document">
		<div class="modal-content">
			<div class="modal-header">
				<h5 class="modal-title text-primary" id="exampleModalLabel"></h5>
				<button class="close" type="button" data-dismiss="modal" aria-label="Close">
					<span aria-hidden="true">×</span>
				</button>
			</div>

			<div class="modal-body">
				<div id="navs-info"></div>
				
				<hr>
				<input type="hidden" id="paciente_id" name="paciente_id">
				<div class="tab-content pt-4 text-xs" id="myTabContent">
					<div id="mensaje"></div>
					<div id="datosPacienteMasInfo" class="tab-pane fade show active" role="tabpanel"
						aria-labelledby="info-tab">
						<div class="table-responsive text-xxs">
							<table class="table table-sm table-bordered ">
								<thead class="table-dark">
									<tr>
										<th colspan="2" class="text-center text-uppercase">Datos personales del paciente</th>
									</tr>
								</thead>
								<tbody>
									<tr>
										<td>N Telefono: </td>
										<td class="text-uppercase" id="telefono"></td>
									</tr>
									<tr>
										<td>Provincia: </td>
										<td class="text-uppercase " id="Prov"></td>
									</tr>
									<tr>
										<td>Canton: </td>
										<td class="text-uppercase" id="Cant"></td>
									</tr>
									<tr>
										<td>Parroquia: </td>
										<td class="text-uppercase" id="Parroq"></td>
									</tr>
									<tr>
										<td>Barrio: </td>
										<td class="text-uppercase" id="barrio"></td>
									</tr>
									<tr>
										<td>Direccion: </td>
										<td class="text-uppercase" id="direccion"></td>
									</tr>

									<tr>
										<td>Fecha de nacimiento: </td>
										<td class="text-uppercase" id="fecha_n"></td>
									</tr>
									<tr>
										<td>Lugar de nacimiento: </td>
										<td class="text-uppercase" id="lugar_n"></td>
									</tr>
									<tr>
										<td>Seguro: </td>
										<td class="text-uppercase" id="Nacionalidad"></td>
									</tr>
								</tbody>
							</table>
						</div>

					</div>
					<div id="datosPacienteContacto" class="tab-pane fade" role="tabpanel" aria-labelledby="paciente-tab">
						<div class="table-responsive text-xxs">
							<table class="table table-sm table-bordered">
								<thead class="table-dark">
									<tr>
										<th colspan="2" class="text-center text-uppercase">Contacto de emergencia</th>
									</tr>
								</thead>
								<tbody>
									<tr>
										<td>Nombre contacto: </td>
										<td class="text-uppercase" id="contacto_nombre"></td>
									</tr>
									<tr>
										<td>Parentezco: </td>
										<td class="text-uppercase" id="contacto_parentezco"></td>
									</tr>
									<tr>
										<td>Direccion: </td>
										<td class="text-uppercase" id="contacto_direccion"></td>
									</tr>
									<tr>
										<td>N Telefono: </td>
										<td class="text-uppercase" id="contacto_telefono"></td>
									</tr>
								</tbody>
							</table>

						</div>
					</div>
					
					
					<div id="datosPacienteCama" class="tab-pane fade" role="tabpanel" aria-labelledby="cama-tab">
						
						<div class="table-responsive text-xxs" id="tableCama">
							<table class="table table-sm table-bordered">
								<thead class="table-dark">
									<tr>
										<th colspan="2" class="text-center text-uppercase">Cama asignada</th>
									</tr>
								</thead>
								<tbody>
									<tr>
										<td>Especialidad: </td>
										<td class="text-uppercase" id="p_especialidad"></td>
									</tr>
									<tr>
										<td>Habitacion: </td>
										<td class="text-uppercase" id="p_habitacion"></td>
									</tr>
									<tr>
										<td>Cama: </td>
										<td class="text-uppercase" id="p_cama"></td>
									</tr>
									<tr>
										<td>Fecha ingreso: </td>
										<td class="text-uppercase" id="p_fecha"></td>
									</tr>
									<tr>
										<td>Causa: </td>
										<td class="text-uppercase" id="p_causa"></td>
									</tr>
								</tbody>
							</table>
						</div>

					</div>
					<div id="datosPacienteDiagnosticos" class="tab-pane fade" role="tabpanel" aria-labelledby="diag-tab">

						<div class="table-responsive text-xxs">
							<?php echo $this->getDiagnosticos();?>
						</div>


					</div>
				</div>
			</div>
			<div class="modal-footer d-flex justify-content-end">
				<button class="btn btn-primary" type="button" data-dismiss="modal">Aceptar</button>

			</div>


		</div>
	</div>
</div> -->