<div class="card border-left-primary">
	<div class="card-header bg-light d-flex justify-content-between align-middle pb-0">
		<h4 class="h4  text-dark"><?php echo $this->titulo; ?>
			<i class="fas fa-fw <?php echo $this->icono; ?> text-dark"></i></h4>
		<nav aria-label="breadcrumb">
			<ol class="breadcrumb bg-transparent  text-xxs p-0 ">
				<li class="breadcrumb-item"><a href="<?php echo $this->baseUrl(); ?>/panel_de_control">
						<i class="fas fa-home "></i>Inicio</a></li>
				<li class="breadcrumb-item text-capitalize">
					<a href="<?php echo $this->baseUrl(); ?>/<?php echo $this->controlador; ?>">
						<i class="fas fa-fw fa-user-injured"></i>
						<?php echo $this->controlador; ?></a></li>
				<li class="breadcrumb-item active text-capitalize" aria-current="page">
					<?php echo $this->accion; ?></li>
			</ol>
		</nav>

	</div>
	<div class="card-body text-xs" id="contenido">
		<div class="d-flex justify-content-end pb-4">
			<form class="needs-validation" method="post" id="form_paciente_busca" name="form_paciente_busca" novalidate>
				<div class="input-group input-group-sm ">
					<input type="text" class="form-control" id="busca_paciente" name="busca_paciente"
						value="<?php if (isset($_GET['id'])) echo $_GET['id']; ?>" placeholder="Buscar por hc o cedula..."
						aria-label="Search" aria-describedby="buscar_paciente_hc" required autocomplete="off">
					<div class="input-group-append">
						<button class="btn btn-primary" type="submit" onclick="BuscaPaciente();">
							<i class="fas fa-search fa-sm"></i>
						</button>
					</div>
					<div class="valid-feedback">
					</div>
					<div class="invalid-feedback">
					</div>
				</div>
			</form>
		</div>
		<form class="needs-validation" method="post" id="paciente_admision" name="paciente_admision" novalidate>
			<div class="row">
				<div class="col-sm-2">
					<div class="form-group">
						<label for="apellido_paterno">Apellido paterno:</label>
						<input type="text" id="apellido_paterno" class="form-control form-control-sm" name="apellido_paterno" maxlength="25"
							required autocomplete="off" onkeyup="this.value = this.value.toUpperCase();"
							pattern="\D{1,25}">
						<div class="valid-feedback">
						</div>
						<div class="invalid-feedback">
						</div>
					</div>
				</div>
				<div class="col-sm-2">
					<div class="form-group">
						<label for="apellido_materno">Apellido materno:</label>
						<input type="text" id="apellido_materno" class="form-control form-control-sm" name="apellido_materno" maxlength="25"
							required autocomplete="off" onkeyup="this.value = this.value.toUpperCase();"
							pattern="\D{1,25}">
						<div class="valid-feedback">
						</div>
						<div class="invalid-feedback">
						</div>
					</div>
				</div>
				<div class="col-sm-2">
					<div class="form-group ">
						<label for="primer_nombre">Primer nombre:</label>
						<input type="text" id="primer_nombre" class="form-control form-control-sm" name="primer_nombre" maxlength="25"
						required autocomplete="off" onkeyup="this.value = this.value.toUpperCase();"
							pattern="\D{1,25}">
						<div class="valid-feedback">
						</div>
						<div class="invalid-feedback">
						</div>
					</div>
				</div>
				<div class="col-sm-2">
					<div class="form-group">
						<label for="segundo_nombre">Segundo nombre:</label>
						<input type="text" id="segundo_nombre" class="form-control form-control-sm" name="segundo_nombre" maxlength="25"
							required autocomplete="off" onkeyup="this.value = this.value.toUpperCase();"
							pattern="\D{1,25}">
						<div class="valid-feedback">
						</div>
						<div class="invalid-feedback">
						</div>
					</div>
				</div>
				<div class="col-sm-2">
					<div class="form-group">
						<label for="cedula">N Cedula:</label>
						<input type="text" id="cedula" class="form-control form-control-sm" name="cedula" maxlength="10" 
						required autocomplete="off" pattern="\d{10}">
						<div class="valid-feedback">
						</div>
						<div class="invalid-feedback">
							Sólo dígitos (10)
						</div>
					</div>
				</div>
				<div class="col-sm-2">
					<div class="form-group">
						<label for="telefono">N Telefono:</label>
						<input type="tel" id="telefono" class="form-control form-control-sm" name="telefono" maxlength="10"
						 required autocomplete="off" pattern="^0+\d{9}">
						<div class="valid-feedback">
						</div>
						<div class="invalid-feedback">
							Formato: 0XXXXXXXXX 
						</div>
					</div>
				</div>
			</div>
			<div class="row">
				<div class="col-sm-2">
					<?php echo $this->getProvincias(); ?>
				</div>
				<div class="col-sm-2">
					<div class="form-group">
						<label for="comboCant">Canton:</label>
						<select class="form-control form-control-sm " name="comboCant" id="comboCant"
							onchange="getParroquias();"  required autocomplete="off" >
						</select>
						<div class='valid-feedback'>
						</div>
						<div class='invalid-feedback'>
						</div>
					</div>
				</div>
				<div class="col-sm-2">
					<div class="form-group">
						<label for="comboParroq">Parroquia:</label>
						<select class="form-control form-control-sm   " name="comboParroq" id="comboParroq" required
							autocomplete="off"  >
						</select>
						<div class='valid-feedback'>
						</div>
						<div class='invalid-feedback'>
						</div>
					</div>
				</div>
				<div class="col-sm-2">
					<div class="form-group">
						<label for="barrio">Barrio:</label>
						<input type="text" id="barrio" class="form-control form-control-sm" name="barrio" required maxlength="50"
							autocomplete="off" maxlength="50" onkeyup="this.value = this.value.toUpperCase();"
							pattern="[[:alnum:]]{1,50}">
						<div class="valid-feedback">
						</div>
						<div class="invalid-feedback">
						</div>
					</div>
				</div>
				<div class="col-sm-4">
					<div class="form-group">
						<label for="direccion">Direccion domiciliaria:</label>
						<input type="text" id="direccion" class="form-control form-control-sm" name="direccion" required maxlength="150"
							autocomplete="off" maxlength="120" onkeyup="this.value = this.value.toUpperCase();"
							pattern="[[:alnum:]]{1,150}">
						<div class="valid-feedback">
						</div>
						<div class="invalid-feedback">
						</div>
					</div>
				</div>
			</div>
			<div class="row">
				<div class="col-sm-2">
					<div class="form-group">
						<label for="fecha_n">Fecha de nacimiento:</label>
						<input type="date" id="fecha_n" class="form-control form-control-sm" name="fecha_n" required
							autocomplete="off">
						<div class="valid-feedback">
						</div>
						<div class="invalid-feedback">
						</div>
					</div>
				</div>
				<div class="col-sm-2">
					<div class="form-group">
						<label for="lugar_n">Lugar de nacimiento:</label>
						<input type="text" id="lugar_n" class="form-control form-control-sm" name="lugar_n" required maxlength="20"
							autocomplete="off" maxlength="20" onkeyup="this.value = this.value.toUpperCase();"
							pattern="[[:alnum:]]{1,20}">
						<div class="valid-feedback">
						</div>
						<div class="invalid-feedback">
						</div>
					</div>
				</div>
				<div class="col-sm-2">
					<?php echo $this->getNacionalidad(); ?>

				</div>
				<div class="col-sm-2">
					<?php echo $this->getGrupo(); ?>
				</div>
				<div class="col-sm-1">
					<?php echo $this->getEdad(); ?>

				</div>
				<div class="col-sm-1">
					<div class="form-group">
						<label for="comboGenero">Genero:</label>
						<select name="comboGenero" id="comboGenero" class="form-control form-control-sm  " required
							autocomplete="off" >
							<option value=""></option>
							<option value="F">F</option>
							<option value="M">M</option>
						</select>
						<div class="valid-feedback">
						</div>
						<div class="invalid-feedback">
						</div>
					</div>
				</div>
				<div class="col-sm-2">
					<?php echo $this->getEstadocivil(); ?>
				</div>
			</div>
			<div class="row">
				<div class="col-sm-2">
					<?php echo $this->getInstruccion(); ?>

				</div>
				<div class="col-sm-2">
					<div class="form-group">
						<label for="ocupacion">Ocupacion:</label>
						<input type="text" id="ocupacion" class="form-control form-control-sm" name="ocupacion" required maxlength="50"
							autocomplete="off" maxlength="50" onkeyup="this.value = this.value.toUpperCase();"
							pattern="\D{1,50}">
						<div class="valid-feedback">
						</div>
						<div class="invalid-feedback">
						</div>
					</div>
				</div>
				<div class="col-sm-3">
					<div class="form-group">
						<label for="trabajo">Empresa donde trabaja:</label>
						<input type="text" id="trabajo" class="form-control form-control-sm" name="trabajo" required maxlength="50"
							autocomplete="off" maxlength="50" onkeyup="this.value = this.value.toUpperCase();"
							pattern="[[:alnum:]]{1,50}">
						<div class="valid-feedback">
						</div>
						<div class="invalid-feedback">
						</div>
					</div>
				</div>
				<div class="col-sm-2">
					<?php echo $this->getTiposeguro(); ?>
				</div>
				<div class="col-sm-3">
					<div class="form-group">
						<label for="referido">Referido de:</label>
						<input type="text" id="referido" class="form-control form-control-sm" name="referido" required maxlength="50"
							autocomplete="off" maxlength="50" onkeyup="this.value = this.value.toUpperCase();"
							pattern="[[:alnum:]]{1,50}">
						<div class="valid-feedback">
						</div>
						<div class="invalid-feedback">
						</div>
					</div>
				</div>
			</div>
			<div class="row">
				<div class="col-sm-3">
					<div class="form-group">
						<label for="contacto_nombre">En caso necesario avisar a:</label>
						<input type="text" id="contacto_nombre" class="form-control form-control-sm" name="contacto_nombre"
							required autocomplete="off" maxlength="50" onkeyup="this.value = this.value.toUpperCase();"
							pattern="\D{1,50}">
						<div class="valid-feedback">
						</div>
						<div class="invalid-feedback">
						</div>
					</div>
				</div>
				<div class="col-sm-3">
					<div class="form-group">
						<label for="contacto_parentezco">Parentezco:</label>
						<input type="text" id="contacto_parentezco" class="form-control form-control-sm"
							name="contacto_parentezco" required autocomplete="off" maxlength="30"
							onkeyup="this.value = this.value.toUpperCase();"
							pattern="\D{1,30}">
						<div class="valid-feedback">
						</div>
						<div class="invalid-feedback">
						</div>
					</div>
				</div>
				<div class="col-sm-4">
					<div class="form-group">
						<label for="contacto_direccion">Direccion:</label>
						<input type="text" id="contacto_direccion" class="form-control form-control-sm"
							name="contacto_direccion" required autocomplete="off" maxlength="150"
							onkeyup="this.value = this.value.toUpperCase();"
							pattern="[[:alnum:]]{1,150}">
						<div class="valid-feedback">
						</div>
						<div class="invalid-feedback">
						</div>
					</div>
				</div>
				<div class="col-sm-2">
					<div class="form-group">
						<label for="contacto_telefono">N Telefono:</label>
						<input type="tel" id="contacto_telefono" class="form-control form-control-sm" name="contacto_telefono"
							required autocomplete="off" maxlength="10"  pattern="^0+\d{9}">
						<div class="valid-feedback">
						</div>
						<div class="invalid-feedback">
							Formato: 0XXXXXXXXX
						</div>
					</div>
				</div>
			</div>
			<div class="row">
				<div class="col-sm-3">
					<?php echo $this->getFormallegada(); ?>

				</div>
				<div class="col-sm-3">
					<div class="form-group">
						<label for="fuente_info">Fuente de informacion:</label>
						<input type="text" id="fuente_info" class="form-control form-control-sm" name="fuente_info" required
							autocomplete="off" maxlength="50" onkeyup="this.value = this.value.toUpperCase();"
							pattern="[[:alnum:]]{1,50}">
						<div class="valid-feedback">
						</div>
						<div class="invalid-feedback">
						</div>
					</div>
				</div>
				<div class="col-sm-4">
					<div class="form-group">
						<label for="institucion">Institucion o persona que entrega al paciente:</label>
						<input type="text" id="institucion" class="form-control form-control-sm" name="institucion" required
							autocomplete="off" maxlength="50" onkeyup="this.value = this.value.toUpperCase();"
							pattern="[[:alnum:]]{1,50}">
						<div class="valid-feedback">
						</div>
						<div class="invalid-feedback">
						</div>
					</div>
				</div>
				<div class="col-sm-2">
					<div class="form-group">
						<label for="institucion_telefono">N Telefono:</label>
						<input type="tel" id="institucion_telefono" class="form-control form-control-sm "
							name="institucion_telefono" required autocomplete="off" maxlength="10"
							pattern="^0+\d{9}">
						<div class="valid-feedback">
						</div>
						<div class="invalid-feedback">
							Formato: 0XXXXXXXXX
						</div>
					</div>
				</div>
			</div>

			<div class=" d-flex justify-content-between">
				<button type="reset" class="btn btn-danger btn-icon-split ">
					<span class="icon text-white-50"><i class="fas fa-ban"></i></span><span class="text">Cancelar</span>
				</button>
				<button type="submit" id="btn_admision" class="btn btn-primary btn-icon-split "
					onclick="AdmisionPaciente();">
					<span class="icon text-white-50"><i class="fas fa-paper-plane"></i></span><span class="text">Registrar
						paciente</span>
				</button>
				<button type="submit" id="btn_edicion" class="d-none btn btn-dark btn-icon-split "
					onclick="EditarAdmisionPaciente();"><span class="icon text-white-50"><i
							class="fas fa-pen"></i></span><span class="text">Actualizar datos</span></button>


			</div>
		</form>
	</div>
</div>