<script>
    $(function () {
        $('#dataTable').DataTable()
    });
</script>
<!-- Page Heading -->
<div class="d-flex justify-content-between py-2">
    <h1 class="h3  text-gray-800 text-capitalize"><?php echo $this->controlador; ?>
        <small class="text-gray-400 text-capitalize"><?php echo $this->accion; ?></small></h1>
    <ol class="breadcrumb bg-light">
        <li class="breadcrumb-item"><a href="<?php echo $this->baseUrl; ?>">
                Inicio</a></li>
        <li class="breadcrumb-item text-capitalize">
            <a href="<?php echo $this->baseUrl; ?>/<?php echo $this->controlador; ?>">
                <?php echo $this->controlador; ?></a></li>
        <li class="breadcrumb-item active text-capitalize" aria-current="page"><?php echo $this->accion; ?></li>
    </ol>
</div>

<!-- DataTales Example -->
<div class="card  shadow ">
    <div class="card-header   d-flex justify-content-between">
        <h4 class="m-0 font-weight-bold text-primary"><?php echo $this->titulo; ?></h4>
        <button type="button"  onclick="agregarModal()" 
        class="btn btn-success btn-sm" >
            <i class="fa fa-plus"></i> Agregar
        </button>
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <?php echo $this->data; ?>
        </div>
    </div>
</div>

<!-- formulario Modal-->
<div class="modal fade" id="formModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
     aria-hidden="true">
    <div class="modal-dialog modal-sm" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel"></h5>
                <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <div class="modal-body">
                <div id="divModal"></div>
                    <div  class="form-group">
                        <label for="nombre_area">Nombre del area:</label>
                        <input type="text"
                        id="nombre_area"
                        class="form-control"
                        name="nombre_area"
                        placeholder="Ingrese el nombre del Area"
                        required autocomplete="off" onkeyup="validar()">
                        <small id="nombreHelp" ></small>
                    </div>
                    <div id="mensaje"></div>
                    <hr>
                    <div class="d-flex justify-content-between">
                        <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancelar</button>
                        <button  type="button" id="btnModal" onclick="InsertarArea();">Aceptar</button>
                    </div>
            </div>
        </div>
    </div>
</div>
<script src="<?php echo $this->baseUrl; ?>/functions/areas.js"></script>
