<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">
  <title><?php echo 'PGCAM - '.$this->titulo; ?></title>
  <!-- Custom fonts for this template-->
  <link href="<?php echo $this->baseUrl(); ?>/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
  <link
    href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
    rel="stylesheet">
<link href="<?php echo $this->baseUrl(); ?>/assets/fonts/fonts.css" rel="stylesheet" type="text/css">
  <!-- Custom styles for this template-->
  <link href="<?php echo $this->baseUrl(); ?>/assets/css/sb-admin-2.min.css" rel="stylesheet">
  <link rel="icon" type="image/vnd.microsoft.icon" href="<?php echo $this->baseUrl(); ?>/favicon.svg">
</head>

<body class="bg bg-gradient-light align-middle">
  <!-- Begin Page Content -->

  <div class="container py-5">

    <!-- 404 Error Text -->
    <div class="row">
      <div class="col-xl-3"></div>
      <div class="col-xl-6 ">
        <div class="card h-100 shadow-lg">
          <div class="card-header bg-light d-flex justify-content-center align-middle ">
            <h4 class="text-gray-800 "><?php echo $this->message ?></h4>
          </div>
          <div class="card-body text-center pb-2">
            <?php if($this->codigo==404){ ?>
            <h1 class="display-1 text-danger">4<i class="fas fa-exclamation-circle "></i>4</h1>
            <h2>Ocurrió un error <i class="fas fa-sad-tear "></i></h2>
            <strong>Mensaje: </strong><span>Lo sentimos, pero no se encontró la página que solicitó</span>
            <?php } else if($this->codigo==500){ ?>
            <h1 class="display-1  text-warning">5<i class="fas fa-exclamation-circle "></i>0</h1>
            <h2>Ocurrió un error <i class="fas fa-sad-tear "></i></h2>
            <strong>Mensaje: </strong><span>Error de la base de datos</span>
            <?php } else if($this->codigo==403){ ?>
              
            <h1 class="display-1 text-info">4<i class="fas fa-exclamation-circle "></i>3</h1>
            <h2>Ocurrió un error <i class="fas fa-sad-tear "></i></h2>
            <strong>Mensaje: </strong><span>Usted no cuenta con los permisos necesarios para acceder a este <?php echo $this->msg ?></span>
            <?php } ?>

          </div>
          <div class="card-footer text-center">
            <a type="button" href="#" onclick="window.history.back();" class="btn btn-dark btn-icon-split ">
              <span class="icon text-white-50"><i class="fas fa-arrow-left"></i></span><span class="text">Regresar a la
                pagina anterior</span>
            </a>
          </div>
        </div>

      </div>
      <div class="col-xl-3"></div>
      
    </div>

    <?php if (isset($this->exception)): ?>

    <h3>Exception information:</h3>
    <p>
      <b>Message:</b> <?php echo $this->exception->getMessage() ?>
    </p>

    <h3>Stack trace:</h3>
    <pre><?php echo $this->exception->getTraceAsString() ?>
  </pre>

    <h3>Request Parameters:</h3>
    <pre><?php echo $this->escape(var_export($this->request->getParams(), true)) ?>
  </pre>

    <?php endif ?>
  </div>
  <!-- /.container-fluid -->

  <!-- Bootstrap core JavaScript-->
  <script src="<?php echo $this->baseUrl(); ?>/vendor/jquery/jquery.min.js"></script>
  <script src="<?php echo $this->baseUrl(); ?>/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

  <!-- Core plugin JavaScript-->
  <script src="<?php echo $this->baseUrl(); ?>/vendor/jquery-easing/jquery.easing.min.js"></script>

  <!-- Custom scripts for all pages-->
  <script src="<?php echo $this->baseUrl(); ?>/assets/js/sb-admin-2.min.js"></script>

  <input type="hidden" name="dir" id="dir" readonly="readonly" value="<?php echo $this->baseUrl(); ?>">

</body>

</html>