
        <!-- Page Heading -->
        <div class="d-flex justify-content-between">
			<h1 class="h3 mb-2 text-gray-800 text-capitalize"><?php echo $this->controlador;?>
			<i class="fas fa-fw fa-heartbeat text-gray-700"></i></h1>
			  <ol class="breadcrumb bg-light">
				 <li class="breadcrumb-item"><a href="<?php echo $this->baseUrl; ?>">
				 Inicio</a></li>
				 <li class="breadcrumb-item text-capitalize">
				 <a href="<?php echo $this->baseUrl; ?>/<?php echo $this->controlador;?>"><?php echo $this->controlador;?></a></li>
				 <li class="breadcrumb-item active text-capitalize" aria-current="page"><?php echo $this->accion;?></li>
			  </ol>
		 </div>
			<!-- DataTales Example -->
			<div class="card  shadow-lg">
			  <div class="card-header d-flex justify-content-between">
				 <h4 class="m-0 font-weight-bold text-primary"><?php echo $this->titulo;?></h4>
				 <nav >
					<div class="nav nav-tabs" id="nav-tab" role="tablist">
						
					  <a class="nav-item nav-link active" id="nav-home-tab" data-toggle="tab" 
					  href="#nav-descripcion" role="tab" aria-controls="nav-home" aria-selected="true">Descripcion</a>
					  <a class="nav-item nav-link" id="nav-profile-tab" data-toggle="tab" 
					  href="#nav-categoria" role="tab" aria-controls="nav-profile" aria-selected="false">Categoria</a>
					  <a class="nav-item nav-link" id="nav-contact-tab" data-toggle="tab" 
					  href="#nav-capitulo" role="tab" aria-controls="nav-contact" aria-selected="false">Capitulo</a>
					</div>
				 </nav>
			  </div>
			  <div class="card-body">
				
				 <div class="tab-content" id="nav-tabContent">
					<div class="tab-pane fade show active" id="nav-descripcion" role="tabpanel" aria-labelledby="nav-home-tab">
						<div class="row">
							<div class="col-sm-2"></div>
							<div class="col-sm-8 d-flex justify-content-center">
									<div class="input-group">
									  <input type="text" id="buscaDescripcion" name="buscaDescripcion" class="form-control bg-light border-1 small" 
									  placeholder="Buscar por descripcion..." 
									  aria-label="Search" aria-describedby="basic-addon2">
									  <div class="input-group-append">
										 <button class="btn btn-primary" type="button">
											<i class="fas fa-search fa-sm"></i>
										 </button>
									  </div>
									</div>
							</div>
							<div class="col-sm-2"></div>
						</div>
						<div class="row">
							<div class="col-sm-12">
								<div class="table-responsive">
							
								</div>
							</div>
						</div>
						
						
					</div>
					<div class="tab-pane fade" id="nav-categoria" role="tabpanel" aria-labelledby="nav-profile-tab">
							<div class="row">
							<div class="col-sm-2"></div>
							<div class="col-sm-8 d-flex justify-content-center">
									<div class="input-group">
									  <input type="text" id="buscaCategoria" name="buscaCategoria" class="form-control bg-light border-1 small" 
									  placeholder="Buscar por categoria..." 
									  aria-label="Search" aria-describedby="basic-addon2">
									  <div class="input-group-append">
										 <button class="btn btn-primary" type="button">
											<i class="fas fa-search fa-sm"></i>
										 </button>
									  </div>
									</div>
							</div>
							<div class="col-sm-2"></div>
						</div>
						<div class="row">
							<div class="col-sm-12">
								<div class="table-responsive">
							
								</div>
							</div>
						</div>
					</div>
					<div class="tab-pane fade" id="nav-capitulo" role="tabpanel" aria-labelledby="nav-contact-tab">
						<div class="row">
							<div class="col-sm-2"></div>
							<div class="col-sm-8 d-flex justify-content-center">
									<div class="input-group">
									  <input type="text" id="buscaCapitulo" name="buscaCapitulo" class="form-control bg-light border-1 small" 
									  placeholder="Buscar por capitulo..." 
									  aria-label="Search" aria-describedby="basic-addon2">
									  <div class="input-group-append">
										 <button class="btn btn-primary" type="button">
											<i class="fas fa-search fa-sm"></i>
										 </button>
									  </div>
									</div>
							</div>
							<div class="col-sm-2"></div>
						</div>
						<div class="row">
							<div class="col-sm-12">
								<div class="table-responsive">
							
								</div>
							</div>
						</div>
					</div>
				 </div>
				 
			  </div>
			</div>

<!-- formulario Modal-->
<div class="modal fade" id="formModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
	 aria-hidden="true">
	<div class="modal-dialog modal-sm" role="document">
		 <div class="modal-content">
			  <div class="modal-header">
					<h5 class="modal-title text-primary" id="exampleModalLabel"></h5>
					<button class="close" type="button" data-dismiss="modal" aria-label="Close">
						 <span aria-hidden="true">×</span>
					</button>
			  </div>
			  <div class="modal-body">
					<input type="hidden" id="piso_id" name="piso_id">
						 
						 <div  class="form-group">
							  <label for="nombre_piso">Nombre del piso:</label>
							  <input type="text"
							  id="nombre_piso"
							  class="form-control "
							  name="nombre_piso"
							  required autocomplete="off" onkeyup="validar()">
							  <small  id="nombreHelp" ></small>
						 </div>
						 <hr>
						 <div class="d-flex justify-content-between">
							  <button class="btn btn-danger" type="button" data-dismiss="modal">Cancelar</button>
							  <div id="accionForm">

							  </div>
						 </div>
			  </div>
		 </div>
	</div>
</div>
<script src="<?php echo $this->baseUrl; ?>/functions/pisos.js"></script>
