<div class="card ">
	<div class="card-header bg-light d-flex justify-content-between align-middle pb-0">
		<h4 class="h4 text-capitalize text-dark"><?php echo $this->controlador; ?>
			<i class="fas fa-fw <?php echo $this->icono; ?> text-dark"></i></h4>
		<nav aria-label="breadcrumb">
			<ol class="breadcrumb bg-transparent  text-xxs p-0 ">
				<li class="breadcrumb-item"><a href="<?php echo $this->baseUrl(); ?>/panel_de_control">
						<i class="fas fa-home "></i>Inicio</a></li>
				<li class="breadcrumb-item text-capitalize">
					<a href="<?php echo $this->baseUrl(); ?>/<?php echo $this->controlador; ?>">
						<i class="fas fa-fw <?php echo $this->icono; ?>"></i>
						<?php echo $this->controlador; ?></a></li>
				<li class="breadcrumb-item active text-capitalize" aria-current="page">
					<?php echo $this->accion; ?></li>
			</ol>
		</nav>
	
	</div>
	<div class="card-body">
		<img class="card-img-top h-50" src="<?php echo $this->baseUrl(); ?>/assets/img/construction.svg" alt="Login">
		<h4 class="display-4 text-center">En construcción</h4>
	</div>
</div>