<div class="card border-left-primary mb-4">
	<div class="card-header bg-light d-flex justify-content-between align-middle pb-0">
		<h4 class="h4 text-capitalize text-dark"><?php echo $this->controlador; ?>
			<i class="fas fa-fw <?php echo $this->icono; ?> text-dark"></i></h4>
		<nav aria-label="breadcrumb">
			<ol class="breadcrumb bg-transparent  text-xxs p-0 ">
				<li class="breadcrumb-item"><a href="<?php echo $this->baseUrl(); ?>/panel_de_control">
						<i class="fas fa-home "></i>Inicio</a></li>
				<li class="breadcrumb-item text-capitalize">
					<a href="<?php echo $this->baseUrl(); ?>/<?php echo $this->controlador; ?>">
						<i class="fas fa-fw <?php echo $this->icono; ?>"></i>
						<?php echo $this->controlador; ?></a></li>
				<li class="breadcrumb-item active text-capitalize" aria-current="page">
					<?php echo $this->accion; ?></li>
			</ol>
		</nav>

	</div>
	<div class="card-body">
		<input type="hidden" name="campoBusqueda" id="campoBusqueda" value="<?php if (isset($_GET['id'])) echo $_GET['id']; ?>">
		<div class="d-flex justify-content-start pb-2">
			<div class="text-center align-content-center " id="exportButtons"></div>

		</div>

		<div id="data_Table" class="table-responsive text-xxs">
			<?php echo $this->data; ?>
		</div>
	</div>
</div>